### ISSUE TITLE
Update paper availability status when it is deposited independently

### ISSUE THREAD

**Issue by a3nm** [dissemin/dissemin#116]
When a researcher deposits a paper in an open repository independently from dissemin, the deposit should be noticed by dissemin to update the paper availability.

Right now this could occur, e.g., in OAI-PMH-retrieved data, but would not be reflected.

Ideally, when a record is noticed for an already known paper that makes the full text available, the paper's availability status should be updated instantly.

A workaround would be to have a button "update this paper" on each paper, or to have an option to "deposit" and give the URL to an existing deposit, as a cue for dissemin to reexamine that paper's availability.

**Comment by p4bl0-** [comment]
I would like to stress out that this is the most urgent issue we have right now, as we do not do real deposit via Dissemin yet.

User experience in the beginning is critical, and as of now people can use Dissemin to see which papers they can deposit, but they have to it directly on the eprint of their choice. They should absolutely be rewarded on their Dissemin page by an augmented "available full texts" counter for that :-).

I think the "update this paper" option is the best option in terms of necessary resources.

**Comment by threonorm** [comment]
An other instance of this problem is  "This ORCID profile does not reference any publication. The ones shown below might be irrelevant or incomplete." that is not removed even when the orcid account is updated.

**Comment by nemobis** [comment]
Related to https://github.com/dissemin/dissemin/issues/88

**Comment by wetneb** [comment]
Now upload to Zenodo is working, and new uploads covered by our sources are automatically taken into account.
