### ISSUE TITLE
LaTeX accents not working properly

### ISSUE THREAD

**Issue by wetneb** [dissemin/dissemin#147]
On Alexander Grothendieck

**Comment by RaitoBezarius** [comment]
Are the documents compiled with XeLaTeX? If no, which compiler was used?

**Comment by wetneb** [comment]
We have no LaTeX compiler in the pipeline: it's only about metadata fragments which include LaTeX-like notations. They are displayed with MathJax in HTML, but internally we need to convert them to plain text. We use https://pypi.python.org/pypi/unicode_tex but it's not perfect:
http://beta.dissem.in/paper/43725/

**Comment by RaitoBezarius** [comment]
Definitely strange, do you have the input encoding for this example?

**Comment by wetneb** [comment]
Yes, sorry, see the commit above
