### ISSUE TITLE
Remove legends with no associated papers

### ISSUE THREAD

**Issue by a3nm** [dissemin/dissemin#151]
In the graph in http://public.dissem.in/researcher/51/ one could remove legends such as  "Unknown/unclear sharing policy (0)" that have no associated papers

**Comment by wetneb** [comment]
If a user is not familiar with the 5 categories we use, wouldn't it be useful for them to see all the categories even if there are no papers in them, to understand the logic behind the classification?

**Comment by a3nm** [comment]
I don't think it's useful to train users to understand categories that they don't see yet. What's the downside with waiting for them to see a paper where the category exists, to understand what's going on?

However I think it's true that the legends should be worded such that any subset of them makes sense.

**Comment by wetneb** [comment]
Can you think of such a wording? Currently, it's not clear that the last 3 ones are "unavailable".

**Comment by a3nm** [comment]
What about:

3. Unavailable but could be deposited
4. Unavailable and editor policy is unclear
5. Unavailable and editor forbids sharing

**Comment by a3nm** [comment]
Another glitch: number 4 may be longer than one line, see e.g., http://public.dissem.in/researcher/205/

**Comment by wetneb** [comment]
It's live on the beta: http://beta.dissem.in/researcher/205/
Not sure how to deal with the length…

**Comment by Phyks** [comment]
Hmm, the links in this issue are all dead (even on regular dissem.in website) :p

What were the remaining issues to tackle here?

**Comment by wetneb** [comment]
I think we can close this indeed!
