### ISSUE TITLE
Dissemin should use SSL [$15]

### ISSUE THREAD

**Issue by a3nm** [dissemin/dissemin#155]
We should support SSL everywhere, and probably use it by default.

However I suggest waiting for Let's encrypt before we try to address that.

I signed us up to their beta program.

**Comment by wetneb** [comment]
They only validated "www.dissem.in" and "dissem.in", so we can't use it for "public.dissem.in" or the beta?

**Comment by RaitoBezarius** [comment]
You cannot use `public.dissem.in` as this was not registered as a subdomain.
Try to ask them another bunch of certificats, they should be comprehensive.

**Comment by wetneb** [comment]
Actually, we have switched to "dissem.in" since, so it should be possible to configure it now.

**Comment by threonorm** [comment]
I just did it for https://beta.dissem.in does it look satisfying to you? It seems to work.

**Comment by cpitclaudel** [comment]
@threonorm: Works nicely for me :)

**Comment by RaitoBezarius** [comment]
What's up for http://dissem.in ? Sounds easy as @threonorm already implemented for the Beta version.

**Comment by threonorm** [comment]
We wanted to make sure it does not break anything. It seems that it is the case. @wetneb  can I do that tonight? Are you ready to react to fix everything I break?

**Comment by wetneb** [comment]
@threonorm yes, go ahead!

**Comment by wetneb** [comment]
LE was set up for association.dissem.in. It should be simple to extend that to dissem.in.

**Comment by RaitoBezarius** [comment]
Closed !
