### ISSUE TITLE
Explain why we need to authenticate users

### ISSUE THREAD

**Issue by wetneb** [dissemin/dissemin#163]
we cannot allow for anonymous deposits

**Comment by RaitoBezarius** [comment]
@wetneb Why not? (some rationale behind this decision)

**Comment by wetneb** [comment]
Actually, you're right, we could try. I have no idea how much spam we would get. That probably means we'd have to moderate deposits, though. Or at least unauthenticated deposits.

But it's very very unusual among open access repositories. The idea is that only authors of a given paper can upload it, so if there is any problem I guess it is good to be able to trace back to the user (although, well, it's fairly simple to use an anonymous email account to sign up for ORCID…).

**Comment by RaitoBezarius** [comment]
@wetneb I understand more the rationale, it makes sense!

I suppose that an author would want to publish a paper anonymously to give it away or to avoid retaliation / censorship.

Anyway, we should focus on must-have features rather than nice-to-have. In this case, I suggest to open a new issue about "anonymous papers" and let it open for further discussion from the community, sounds good?

**Comment by wetneb** [comment]
Yes, why not, but "anonymous uploads" is more precise, as the (supposed) authors of the papers are present in the metadata anyway. (Currently we only allow uploads of papers whose metadata was provided to us by one of our sources.)

**Comment by a3nm** [comment]
I'm not sure that allowing anonymous users to deposit papers is a great idea. We'd have to ask around, but I think that many researchers would be surprised to see that their papers have been re-hosted on an open access repository by someone else without their consent.

**Comment by RaitoBezarius** [comment]
@a3nm That's a good point!
When I thought of "anonymous paper", I was thinking of paper that someone has written but did not wanted to be recognized, no authors, nothing. Just a free contribution.

Now the question is: how can we coordinate this, I suggest that we put some explanations for users about authentication. Then we close this.

Meanwhile, we can open another long-running issue about "Should we support anonymous deposits for anonymous authors?", how does it sounds?

**Comment by wetneb** [comment]
I don't think dissemin is suited for anonymously authored papers (everywhere in the code we assume that each paper has at least one author), so even if the user could be unauthenticated, the paper would need to have an author… So, no, I don't think anonymity is useful here. Everybody in academia assumes a paper is explicitly authored by someone (although sometimes pseudonyms can be used).
