### ISSUE TITLE
Be bolder in proposing uploads to the users

### ISSUE THREAD

**Issue by wetneb** [dissemin/dissemin#165]
- [ ] Change the labels "Could be shared" -> "Has to be shared"
- [ ] Add a sentence explaining "45 papers are available. 15 more could be in open access…"

**Comment by wetneb** [comment]
"Has to be shared" is too extreme, only valid when the researcher is mandated by its institution or funder. "Should be shared", maybe?

**Comment by nemobis** [comment]
This sounds in conflict with https://github.com/dissemin/dissemin/issues/150

**Comment by wetneb** [comment]
indeed, closing
