### ISSUE TITLE
Some papers are not imported from ORCID profiles

### ISSUE THREAD

**Issue by wetneb** [dissemin/dissemin#169]
When they are written manually. Either include them (by assuming that the only author is the ORCID's holder) or explain to the user why we have not included them.

**Comment by wetneb** [comment]
Changes needed: keep track, for each researcher, of:
- the number of papers associated to its ORCID profile (Author.objects.filter(affiliation=doi).count)
- the number of papers ignored from its ORCID profile

**Comment by RaitoBezarius** [comment]
I think that we can close this one, fixed in #233

**Comment by wetneb** [comment]
Yes indeed!
