### ISSUE TITLE
Remove the editor in the publications lists

### ISSUE THREAD

**Issue by wetneb** [dissemin/dissemin#171]
"surtout que là il est à côté du bouton "download" et ça sous-entend pour les gens qu'on le télécharge depuis ou grace à l'éditeur du coup"

**Comment by Lysxia** [comment]
I think the publisher is still useful to know: sometimes we refer to papers by the conference they appeared in, and it also helps to disambiguate papers with similar titles. Nevertheless I agree that the button being right next to it is confusing. Maybe move it to a separate line, and indicate the source when it's "available from the authors"?

    {{ authors }}
    {{ title }}
    {{ publisher }}
    {{ download_buttion }} | {{ source }}

**Comment by wetneb** [comment]
That sounds great!
