### ISSUE TITLE
Wrong PDF url from PMC

### ISSUE THREAD

**Issue by wetneb** [dissemin/dissemin#183]
Identifier: ftpubmed:oai:pubmedcentral.nih.gov:3631525

**Comment by RaitoBezarius** [comment]
Could you explain more this bug? (sorry not familiar with research terms :see_no_evil:)

**Comment by wetneb** [comment]
Sorry, yes, this is not clear at all. When importing OAI records from PubMedCentral, multiple URLs are provided in the record:

<pre>
&lt;base_dc:dc xmlns:base_dc="http://oai.base-search.net/base_dc/" xmlns:dc="http://purl.org/dc/elements/1.1/" xsi:schemaLocation="http://oai.base-search.net/base_dc/         http://oai.base-search.net/base_dc/base_dc.xsd"&gt;
  &lt;dc:title&gt;Measurement in Comparative Effectiveness Research&lt;/dc:title&gt;
  &lt;dc:creator&gt;Chubak, Jessica&lt;/dc:creator&gt;
  &lt;dc:creator&gt;Rutter, Carolyn M.&lt;/dc:creator&gt;
  &lt;dc:creator&gt;Kamineni, Aruna&lt;/dc:creator&gt;
  &lt;dc:creator&gt;Johnson, Eric A.&lt;/dc:creator&gt;
  &lt;dc:creator&gt;Stout, Natasha K.&lt;/dc:creator&gt;
  &lt;dc:creator&gt;Weiss, Noel S.&lt;/dc:creator&gt;
  &lt;dc:creator&gt;Doria-Rose, V. Paul&lt;/dc:creator&gt;
  &lt;dc:creator&gt;Doubeni, Chyke A.&lt;/dc:creator&gt;
  &lt;dc:creator&gt;Buist, Diana S.M.&lt;/dc:creator&gt;
  &lt;dc:description&gt;Comparative effectiveness research (CER) on preventive services can shape policy and help patients, their providers, and public health practitioners select regimens and programs for disease prevention. Patients and providers need information about the relative effectiveness of various regimens they may choose. Decision makers need information about the relative effectiveness of various programs to offer or recommend. The goal of this paper is to define and differentiate measures of relative effectiveness of regimens and programs for disease prevention. Cancer screening is used to demonstrate how these measures differ in an example of two hypothetic screening regimens and programs.&lt;/dc:description&gt;
  &lt;dc:language&gt;en&lt;/dc:language&gt;
  &lt;dc:date&gt;2013-05&lt;/dc:date&gt;
  &lt;dc:identifier&gt;http://www.ncbi.nlm.nih.gov/pmc/articles/PMC&lt;/dc:identifier&gt;
  &lt;dc:identifier&gt;http://www.ncbi.nlm.nih.gov/pubmed/23597816&lt;/dc:identifier&gt;
  &lt;dc:identifier&gt;http://dx.doi.org/10.1016/j.amepre.2013.01.006&lt;/dc:identifier&gt;
  &lt;dc:subject&gt;Article&lt;/dc:subject&gt;
  &lt;dc:type&gt;Text&lt;/dc:type&gt;
  &lt;base_dc:typenorm&gt;0000&lt;/base_dc:typenorm&gt;
  &lt;base_dc:oa&gt;1&lt;/base_dc:oa&gt;
  &lt;base_dc:collection&gt;ftpubmed&lt;/base_dc:collection&gt;
  &lt;base_dc:collname&gt;PubMed Central (PMC)&lt;/base_dc:collname&gt;
  &lt;base_dc:continent&gt;cna&lt;/base_dc:continent&gt;
  &lt;base_dc:country&gt;us&lt;/base_dc:country&gt;
  &lt;base_dc:lang&gt;eng&lt;/base_dc:lang&gt;
  &lt;base_dc:year&gt;2013&lt;/base_dc:year&gt;
  &lt;base_dc:link&gt;http://www.ncbi.nlm.nih.gov/pmc/articles/PMC&lt;/base_dc:link&gt;
  &lt;base_dc:rights&gt;&#169; 2013 American Journal of Preventive Medicine. Published by Elsevier Inc. All rights reserved.&lt;/base_dc:rights&gt;
&lt;/base_dc:dc&gt;
</pre>

We extract "http://www.ncbi.nlm.nih.gov/pmc/articles/PMC" as the URL of the paper in the repository, whereas it should be "http://www.ncbi.nlm.nih.gov/pubmed/23597816". I have no idea how to select the "right" URL in general.

**Comment by wetneb** [comment]
The bug can be observed here: http://beta.dissem.in/10.1016/j.amepre.2013.01.006
The faulty URL extractor is here: https://github.com/dissemin/dissemin/blob/master/backend/extractors.py#L95

**Comment by wetneb** [comment]
This is actually a bug from PubMedCentral itself, so let's close this.

**Comment by RaitoBezarius** [comment]
Did you open an issue or mailed on PMC?
If so, let's add a reference here to track the issue for future reviews?

On Wed, Apr 6, 2016, 19:48 Antonin <notifications@github.com> wrote:

> Closed #183 <https://github.com/dissemin/dissemin/issues/183>.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/dissemin/dissemin/issues/183#event-617197763>
>
-- 

Ryan Lahfa, de mon téléphone.

**Comment by wetneb** [comment]
I have only observed this bug for that particular paper, so I'm not sure I'll bother ^^

**Comment by RaitoBezarius** [comment]
Well, it's alright, if it happens again, let's report it then! I think that
it's a good idea to add an entry to a FAQ about this problem?

On Wed, Apr 6, 2016, 20:31 Antonin <notifications@github.com> wrote:

> I have only observed this bug for that particular paper, so I'm not sure
> I'll bother ^^
>
> —
> You are receiving this because you commented.
>
> Reply to this email directly or view it on GitHub
> <https://github.com/dissemin/dissemin/issues/183#issuecomment-206505620>
>
-- 

Ryan Lahfa, de mon téléphone.

**Comment by wetneb** [comment]
I think it's a very very minor bug, so I wouldn't even bother doing that ^^ But I'm probably too lazy.

**Comment by RaitoBezarius** [comment]
@wetneb Haha, you're right, your time is more valuable on more complicated issues :+1: !
