### ISSUE TITLE
Better URLs with slugified names

### ISSUE THREAD

**Issue by wetneb** [dissemin/dissemin#185]
Suggestions:
* http://dissem.in/researcher/3257/ should be something like http://dissem.in/r/3257/Bernard-Julia
* http://dissem.in/paper/108847/ should be something like http://dissem.in/p/108847/Gravitational_duality_near_de_Sitter_space
and so on…

Add HTTP redirects from the old URLs to the new ones.

**Comment by Lysxia** [comment]
1. When given an incorrect slug, should we redirect, 404, or just serve the page normally?

2. Do you also want to assign a letter to `publisher/`?

3. It looked fun (for me) to do, but maybe I should wait for #199 (Remove latex in title), at least for papers?

**Comment by wetneb** [comment]
I think it's not necessary to check the slug (for instance ResearchGate doesn't).
A letter for publishers would be interesting too, why not!
If we don't check for slugs, then we don't even need #199, right?

**Comment by RaitoBezarius** [comment]
@Lysxia I don't have a lot of time to tackle #199 right now, so you can go ahead !
