### ISSUE TITLE
Add bibtex export [$15]

### ISSUE THREAD

**Issue by wetneb** [dissemin/dissemin#186]
It could be possible to generate bibtex records from paper pages (and ideally in other formats too).

**Comment by cpitclaudel** [comment]
Connects to #211 (doai.org content negociation) :)

**Comment by wetneb** [comment]
See also issue #219

**Comment by Phyks** [comment]
Which record should be exported? Typically, for [this paper](http://dissem.in/p/8652/autonomization-of-monoidal-categories) should there be an "export to Bibtex" button for any available record or just for the paper itself?

I think this issue could be solved quite easily with code such as https://github.com/Phyks/libbmc/blob/master/libbmc/doi.py#L188-L209 (for records with DOIs), https://github.com/Phyks/libbmc/blob/master/libbmc/repositories/arxiv.py#L276-L306 (for arXiv, and similar codes for any repo-specific exports) and https://github.com/Phyks/libbmc/blob/master/libbmc/bibtex.py#L17-L30 (as a fallback, using the information we have about the paper).

**Comment by wetneb** [comment]
I think it would be simpler to have just one BibTeX record per paper. I think it would be nice to have both the DOI and the link to the preprint in the BibTeX when they are both available. Maybe @a3nm and @p4bl0- have more thoughts about what the perfect BibTeX record should look like?

**Comment by a3nm** [comment]
I guess there could be an option to "export to bibtex", both for individual papers and for pages that list papers (e.g., search results, or list of papers by one author).

I guess we should do like Google Scholar and use LASTNAME2042FIRSTTITLEWORD as a citation key.

It would be nice to include the DOI and URL in a specific field. It would be even nicer if the title of the paper could be clickable to point to the URL or DOI, but doing it by hand (with an `\href`) is ugly. Apparently this can be done by the surrounding document using something [like this](https://tex.stackexchange.com/questions/207004/is-it-possible-to-make-a-reference-clickable-without-showing-its-doi-or-url-fiel) but I've never tried it.

**Comment by Phyks** [comment]
I did a first draft in https://github.com/dissemin/dissemin/pull/647#pullrequestreview-217214655 for a single paper (from the paper details page) export to Bibtex. Please, feel free to comment and review this to fit the need :)

Once single paper export is fine, doing export of a list of results (or profile page) should not be much harder.

Might be worth also letting users export citation to plain text and RIS (used by End Note apparently) as well?

**Comment by Phyks** [comment]
Closing, let us continue the discussion in #666.
