### ISSUE TITLE
Let researchers do a "resync" of their profile

### ISSUE THREAD

**Issue by Phyks** [dissemin/dissemin#196]
Sometimes import of ORCID profiles or lookup for publications fail, resulting in incomplete profile.

Researchers could be allowed to trigger a refresh of their profile and publications list manually.

**Comment by Phyks** [comment]
Ah, missed it was possible once connected. But could be a good idea to let visitors trigger it as well.

**Comment by wetneb** [comment]
It's not available yet, that's just because you're an admin.
