### ISSUE TITLE
Add some links to other views

### ISSUE THREAD

**Issue by Phyks** [dissemin/dissemin#197]
On the homepage, we can only look for a researcher. However, when browsing a bit dissem.in, we can find other (interesting!) pages such as http://dissem.in/publishers. Why not adding links to these pages to the homepage?

**Comment by Phyks** [comment]
Conversely, there is a "publisher" view, but no "journal" view. Could be useful to explore the data from SHERPA/Romeo and have nice summaries by journals.

**Comment by wetneb** [comment]
These views do exist but are hidden for political reasons ^^

**Comment by Phyks** [comment]
Ah, I see =(
