### ISSUE TITLE
JSON bug when going back to the results

### ISSUE THREAD

**Issue by wetneb** [dissemin/dissemin#198]
http://pintoch.ulminfo.fr/094450080c/screen.png
-> just use a different url for the JSON version of the search view

**Comment by wetneb** [comment]
This bug is happening again, the different URL might have been lost during a refactoring.

**Comment by Phyks** [comment]
How did you triggered this? I cannot reproduce so far :/

**Comment by wetneb** [comment]
- Go to a search view
- change the search parameters so that the search results are updated dynamically
- click on one of the search results
- use the "back" button of the browser
- the browser returns the latest version of the previous page that it has fetched, which was the JSON version (due to the different request headers being set).

This happens with Firefox for me (haven't checked Chromium).

**Comment by Phyks** [comment]
Haha, weird I can reproduce in Chromium but not in Firefox! Thanks for the details, I can reproduce it now :)

**Comment by Phyks** [comment]
Indeed, seems it's coming from https://github.com/dissemin/dissemin/blame/master/papers/views.py#L149.

I guess `context['ajax_url']` should be the `/api/search` view URL instead.

**Comment by wetneb** [comment]
It's not quite the same thing as `/api/search` as the ajax url must currently return a rendered version of the paper list, wrapped in JSON (see the screenshot above). Yes that's ugly.

**Comment by Phyks** [comment]
Note to self: It was removed as part of f88864afbb638880e229f0a9d74964dab922266f.
