### ISSUE TITLE
Some untracked files in the VM

### ISSUE THREAD

**Issue by Phyks** [dissemin/dissemin#203]
Following the [instructions for the VM](http://dev.dissem.in/doc/vm.html) there is a problem with `./pull_and_update.sh` due to the fact that there is untracked `celery.sh` and modified `dissemin/settings.py` file.

Easy fix is to `git stash` and `rm celery.sh` before updating, but would be better if it works out of the box, I guess :)

**Comment by wetneb** [comment]
oops sorry, yes indeed.

**Comment by wetneb** [comment]
Should be fixed now.
