### ISSUE TITLE
Users should be able to choose the language

### ISSUE THREAD

**Issue by RaitoBezarius** [dissemin/dissemin#205]
Hi there!

I wondered about if there were plans for translating dissem.in to English, I think this is a great opportunity to make it more known and -- maybe get more contributors?

What do you think?

**Comment by a3nm** [comment]
dissem.in is already available in English. I suspect you can get the English version by changing the Accept-Language headers sent by your Web browser.

However your bug report may suggest that it would be better to have a visible option to allow people to switch to a different language. @wetneb, what do you think? Is there already such an option?

**Comment by RaitoBezarius** [comment]
@a3nm That's awesome, but yeah, my browser is in French so I suppose that Content negotiation has done its job.

Indeed, putting a visible option to switch to a different language would be really interesting.

**Comment by wetneb** [comment]
It's quite straightforward to implement:
https://docs.djangoproject.com/en/1.9/topics/i18n/translation/#the-set-language-redirect-view
