### ISSUE TITLE
Incorrect links in beta version warning on land page

### ISSUE THREAD

**Issue by bienvenu** [dissemin/dissemin#207]
None of the links work for me on the beta warning that is displayed on top of the landpage, as a result of extra backslashes:

```html
<a href=\"http://dissem.in/\">dissem.in</a> is currently in public beta.  Please, let us know about any issue you might have, either on <a href=\"https://github.com/dissemin/dissemin/\">Github</a> or by email at <a href=\"mailto:bugs@dissem.in\">bugs@dissem.in</a>.
```

Clicking on them redirects me to, e.g., `http://dissem.in/%5C%22http://dissem.in/%5C%22`

**Comment by wetneb** [comment]
@bienvenu Oops, thank you very much for reporting this!
