### ISSUE TITLE
ORCID source: use bibtex as fallback when CrossRef metadata fails

### ISSUE THREAD

**Issue by cpitclaudel** [dissemin/dissemin#212]
Here's an example: http://dissem.in/paper/155992/

The record was imported directly from my ORCID profile (probably) and the metadata has one link to Zenodo (the DOI link), and one to MIT Dspace (the handle link), both of which are open repositories; however, Dissemin doesn't detect that.

**Comment by wetneb** [comment]
It does look at DOI fields. This issue is ORCID's fault, really (I will not reproduce here my usual rant about this issue though). It's too long to explain, but I'll try to write a workaround soon (funny hint: this is due to the fact that you have an accent in your first name!!)

**Comment by cpitclaudel** [comment]
> I'll try to write a workaround soon (funny hint: this is due to the fact that you have an accent in your first name!!

Urgh. At least it's not as bad as Google Scholar ignoring authors whose name contains more than one dash :) Thanks for working on this!

**Comment by cpitclaudel** [comment]
👍
