### ISSUE TITLE
Dissemin shouldn't suggest uploading Zenodo papers to Zenodo

### ISSUE THREAD

**Issue by cpitclaudel** [dissemin/dissemin#213]
Related to #212 (same [example](http://dissem.in/paper/155992/)): when a DOI is `10.*/zenodo.*`, Dissemin probably shouldn't suggest re-uploading the paper to Zenodo, right?

Or is there anything wrong with that particular upload?

**Comment by wetneb** [comment]
That's right, we should do that check, thanks.
