### ISSUE TITLE
Dissemin and Blockchain, how can they fit together?

### ISSUE THREAD

**Issue by RaitoBezarius** [dissemin/dissemin#218]
Hi there!

I wanted to open this issue to gather thoughts on how can Dissemin and Blockchain concepts can fit together.

To put it simply, my understanding is that: Dissemin could offer to researchers to put their papers inside of a blockchain and provide an unalterable proof of their public paper forever [^1].

Nevertheless, I suppose that we all have different opinions, as an "open access policy enforcement tool", I believe that writing an unalterable proof is really interesting, sharing the paper inside the proof is even more interesting.

We can discuss details like: should we use [Ethereum](ethereum.org) which is known also as a:

> a blockchain with a built-in fully fledged Turing-complete programming language

Or whether it is relevant that Dissemin offers this kind of service to its researchers.

Let's keep it open so that people can pour their ideas and express their enthusiasm.

What do you think?

[^1]: Well, forever here means as long as every one of the relevant blockchain network is online (on the other hand, if no one is online, that means kinda the network is dead, would you imagine Bitcoin going offline for a few seconds? Me too.)

_Disclaimer: I am a student, not a researcher :D._

**Comment by wetneb** [comment]
Woah, I did not know Ethereum, that's interesting. :-)
I don't think blockchain-based technology fits im our landscape though (but sure, we can keep the issue open ^^).

**Comment by nemobis** [comment]
> put their papers inside of a blockchain and provide an unalterable proof of their public paper forever

Isn't this what a repository is for, e.g. Zenodo?

**Comment by RaitoBezarius** [comment]
> > put their papers inside of a blockchain and provide an unalterable proof of their public paper forever

> Isn't this what a repository is for, e.g. Zenodo?

Not exactly, there is no guarantee that Zenodo won't alter your paper.

Stupid example: I upload a paper X on Zenodo, Zenodo decides to change the paper X to X' (database edition), my paper is altered.

**Comment by wetneb** [comment]
Go explain that to librarians :-P

**Comment by wetneb** [comment]
Closing this discussion to clean up the issues list.
