### ISSUE TITLE
The future of the DOI proxy in Dissemin

### ISSUE THREAD

**Issue by RaitoBezarius** [dissemin/dissemin#230]
As discussed with @wetneb over IRC, we think that:

The DOI proxy won't be that useful in the future if Dissemin handles everything about metadata.
Furthermore, we don't think that it's relevant to continue expecting that every instance of Dissemin should come with its proper DOI proxy (per university, etc...).

We want to converge towards a Dissemin DOI proxy service, so that deploying Dissemin is simpler!

**Comment by wetneb** [comment]
The same is true of the RoMEO proxy and the BASE proxy ^^

**Comment by wetneb** [comment]
We agree, so there's no issue here - happily closing.
