### ISSUE TITLE
Inform about the origin of papers (ORCID / CrossRef / ...)

### ISSUE THREAD

**Issue by RaitoBezarius** [dissemin/dissemin#241]
For debugging purpose and beyond (maybe), we should store the origin of the papers.

If I fetch a paper using ORCID, the origin is ORCID.
And so on.

The changes would be to add a TextField in Paper or BarePaper and populate it during the fetching process.

**Comment by wetneb** [comment]
But the thing is: metadata comes from many different sources!
These sources are the OaiSources of the OaiRecords associated with the
paper (once I'll merge my publication-to-oairecord branch).

For instance, the list of authors is obtained by merging the lists of
authors given by each source.

**Comment by RaitoBezarius** [comment]
Oh, I understand, yeah, you're right.
So once you merge your branch, could we get the list of origins, do you think?

Hmm. I would have thought about a history of paper construction where each mutation of the paper (authors merging, new metadata) would create a new entry in the history.

And then, we can review the history for debugging purpose, how does it sounds? Would that be useful?

**Comment by wetneb** [comment]
I think it would be quite heavy to store all intermediate versions - we can already reconstruct them by looking at the OaiRecords associated with a paper for debugging purposes.
