### ISSUE TITLE
CiteseerX: cached versions not always available for download

### ISSUE THREAD

**Issue by wetneb** [dissemin/dissemin#243]
Why isn't there any full text here?
http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.307.6919
Can we detect that from the OAI metadata?

**Comment by RaitoBezarius** [comment]
Wait, I can download the cached version and it seems to contain the full text, was it a temporary issue / bug ?

**Comment by wetneb** [comment]
It's something that seems to depend on the time / IP address. I have observed cases where two different machines were observing a different page at the same time. Arguably this is a bug in citeseerx rather than dissemin, so maybe we could close this (but it's annoying when visitors are redirected to a page and they can't download the PDF).
