### ISSUE TITLE
Update git on VM

### ISSUE THREAD

**Issue by threonorm** [dissemin/dissemin#247]
The VM is using wetneb/dissemin, so when we push from the virtual machine we get : 
This repository moved. Please use the new location.

**Comment by wetneb** [comment]
Add sphinx to the VM

**Comment by threonorm** [comment]
Add mock to the VM

**Comment by threonorm** [comment]
code duplication between dissemin/src and dissemin/.src .

**Comment by RaitoBezarius** [comment]
Can I suggest to deprecate the VM and use Vagrant with #261 ?

**Comment by wetneb** [comment]
I agree. Closing this.
