### ISSUE TITLE
Implement affiliation lookup field

### ISSUE THREAD

**Issue by wetneb** [dissemin/dissemin#248]
Based on the javascript present in HAL's own deposit interface (that uses jQuery), create a Django field with the same autocompletion.

HAL (preprod) deposit interface: https://halv3-preprod.archives-ouvertes.fr/submit/index
Django fields reference: https://docs.djangoproject.com/en/1.9/ref/forms/fields/
AURéHAL reference: https://api.archives-ouvertes.fr/docs/ref/resource/structure

**Comment by wetneb** [comment]
We should create a custom field with an accompanying JS code that calls the HAL API on the fly. (We don't cache structures in dissemin.) The structure ID (a number) is returned in a hidden field. If the user did not pick any structure from the autocomplete the hidden field should contain the plain text entered by the user. Server-side, we should validate the structure ID (if provided) by checking it against the API, or create a new structure (during deposition) with the label provided.

**Comment by RaitoBezarius** [comment]
Moreover, I guess the affiliation lookup field have to be added in this form: https://github.com/dissemin/dissemin/blob/beta/deposit/hal/forms.py

**Comment by wetneb** [comment]
@RaitoBezarius yes exactly!

**Comment by wetneb** [comment]
Actually, not exactly: the latest version is on the hal branch:
https://github.com/dissemin/dissemin/blob/hal/deposit/hal/forms.py

**Comment by wetneb** [comment]
The affiliation field is now live.
