### ISSUE TITLE
Reach out to authors of depositable DOIs used in Wikipedia

### ISSUE THREAD

**Issue by nemobis** [dissemin/dissemin#251]
It would be nice to make a list of authors who
- have at least one publication cited on a Wikipedia article via the DOI,
- and that publication is paywalled,
- and Dissemin is able to list at least one depositable publication of theirs (keeping in mind https://github.com/dissemin/dissemin/issues/215 ).

Such list could then be used by someone (e.g. Wikimedia Foundation, see https://meta.wikimedia.org/w/index.php?title=Talk%3AThe_Wikipedia_Library&type=revision&diff=15669109&oldid=15488619 ) to encourage usage of Dissemin to deposit said publications.

**Comment by wetneb** [comment]
That's surely doable. Actually it should be enough to use the API (http://dev.dissem.in/api.html), just like what oabot does, tracking the publisher's policy in addition.

**Comment by nemobis** [comment]
Antonin, 02/06/2016 23:33:
> That's surely doable. Actually it should be enough to use the API
> (http://dev.dissem.in/api.html), just like what oabot does, tracking the
> publisher's policy in addition.

Right. I'm querying the API for Italian Wikipedia DOIs to start with, 
and most of them are not found (status 400). For these one can assume 
that the publication is not available in a "real" repository (even 
though maybe it's buried in some Elsevier wasteland like SSRN) an should 
ask CrossRef+RoMEO for publication details and journal policy, right?

**Comment by wetneb** [comment]
HTTP status 400 should only be returned when your query was invalid (invalid DOI in your case, I guess). This is curious if the DOIs come from wikipedia. Can you show me your code?
If you are querying by DOI, it might be easier to use the dedicated endpoint `http://dissem.in/api/<your_doi_comes_here>`.

**Comment by nemobis** [comment]
Antonin, 03/06/2016 11:40:
> HTTP status 400 should only be returned when your query was invalid
> (invalid DOI in your case, I guess). This is curious if the DOIs come
> from wikipedia. Can you show me your code?

Good point, I had forgotten to percent-decode some of the DOIs. Much 
better now!

**Comment by nemobis** [comment]
I attach some example partial lists made with [doi-doai-openaccess.py --depositable](https://github.com/nemobis/bots/blob/master/doi-doai-openaccess.py) (about 40000 DOIs from some 140 wikis).

[doi-doai-dissemin.zip](https://github.com/dissemin/dissemin/files/298780/doi-doai-dissemin.zip)

**Comment by nemobis** [comment]
I notice that https://api.crossref.org/ often doesn't return affiliation for a DOI, while https://api.elsevier.com/documentation/AUTHORSearchAPI.wadl maybe returns affiliation ID more often and from that one can get something like https://api.elsevier.com/documentation/retrieval/affiliationRetrievalResp.json

**Comment by wetneb** [comment]
Interesting! Thanks for pointing that out.

**Comment by nemobis** [comment]
I see that there is https://github.com/leereilly/swot to validate university email addresses. It might still be easier to just mass-download the papers and parse the email addresses contained in them...

**Comment by wetneb** [comment]
The Open Access button has put a lot of effort into retrieving email addresses of authors, maybe @JosephMcArthur has ideas about that?

**Comment by nemobis** [comment]
Thanks for mentioning it. I see they have a few issues on the matter: https://github.com/OAButton/discussion/issues/490 (and https://github.com/OAButton/discussion/issues/648), https://github.com/OAButton/discussion/issues/725

**Comment by nemobis** [comment]
Back to the devils... Web of Science seems pretty neat: http://ip-science.interest.thomsonreuters.com/sample-data/
There is a python client: https://github.com/enricobacis/wos
I've registered but login failed from home.

The Elsevier API has a ratelimit of 5000 every 7 days, quite reasonable. I registered but did not try yet.

Will try again from my institution.

**Comment by nemobis** [comment]
FYI I'm now sending out a few thousands of invites for Dissemin usage. The interest so far is high, some 10 % of recipients click; but I'm not able to quickly gauge the traffic generated on Dissemin (let alone the actual uploads). Absent other data sources, I plan to just see if the amount of self-archived DOIs increases in the next few weeks.

**Comment by wetneb** [comment]
@nemobis that's fantastic, thanks a lot! But be aware that there are still some important bugs that might put users off - mainly the fact that we can miss full texts for various reasons. (For instance, #431). I unfortunately do not have that much time to look into them, but I would think it would be better to solve them before doing too much publicity for the service.

**Comment by nemobis** [comment]
Antonin Delpeuch, 08/08/2017 12:48:
> it would be 
> better to solve them before doing too much publicity for the service.

Sure, but I consider this to be still a rather minor test: out of 
hundreds of thousands of Wikipedia citations I got down to a few 
thousands by requiring Italian usage, DOI, ease of contact for the 
author. I sampled the DOIs manually and Dissemin is generally correct on 
them.

I suggest to see what's the response and whether the impact on Dissemin 
is dramatic; then of course if you want me/us to not advertise Dissemin 
further I'll take it out.

Federico

**Comment by wetneb** [comment]
@nemobis Sure! Thank you so much again, that is very welcome!

Ideally we could also think about some tighter integration with OAbot, as you are focusing on DOIs extracted from Wikipedia. But for that we would first need to run OAbot on itwiki…

**Comment by nemobis** [comment]
Speaking of which, I was looking for a dump of OAbot DOIs on en.wiki, is there such a thing?

**Comment by wetneb** [comment]
There is a dump of all the citations of enwiki, as parsed by OAbot: https://zenodo.org/record/55004
But they are not annotated with self-archiving policies of publishers.

**Comment by nemobis** [comment]
I ended up running mwcites and cleaning up a bit, see https://github.com/mediawiki-utilities/python-mwcites/issues/7#issuecomment-322008753
Now I'm extracting the information for those DOIs, should be done in a couple days.

**Comment by nemobis** [comment]
I posted a summary on https://lists.wikimedia.org/pipermail/openaccess/2017-August/000226.html  (with example text; more or less the same you had already seen).

Meanwhile, the latest round of emails from 4 days ago has reached almost 40 % open rate and 14 % click rate (after discounting bounces). The numbers for deposits and replies I'll check in a couple weeks.

**Comment by nemobis** [comment]
A revised message is going out now to a few thousands more authors. We've got about 50 deposits in the last 3 hours.

**Comment by jibe-b** [comment]
Dear @nemobis, may I ask you the text/subject of the email that gave the best rate of upload?

cc @JosephMcArthur

**Comment by nemobis** [comment]
jibe-b, 10/03/2018 10:23:
> Dear @nemobis <https://github.com/nemobis>, may I ask you the 
> text/subject of the email that gave the best rate of upload?

I'm afraid I don't have such detailed data, I just adapted the text 
along the way while checking the Dissemin upload feed to see how many 
and how good deposits arrived.

**Comment by jibe-b** [comment]
ok, no worries

**Comment by wetneb** [comment]
Closing as this campaign was successfully run! Congratulations again to @nemobis for the huge effort and very nice success!
