### ISSUE TITLE
Locked ORCID gives internal error

### ISSUE THREAD

**Issue by nemobis** [dissemin/dissemin#252]
http://dissem.in/0000-0002-2803-9471/ reliably produces an internal error; http://orcid.org/0000-0002-2803-9471 says "Given Names Deactivated Family Name Deactivated – This ORCID Record is temporarily locked" and I get an internal error for other locked ORCIDs I can find, like http://dissem.in/0000-0003-3387-820X/ , so I guess that's the reason.

**Comment by wetneb** [comment]
Thanks a lot!
