### ISSUE TITLE
Tous les articles de Natalie Portman ne sont pas sur son profil

### ISSUE THREAD

**Issue by jilljenn** [dissemin/dissemin#256]
Bonjour, à l'occasion des 35 ans de Natalie Portman, je me suis demandé à quoi pourrait ressembler [son profil dissem.in](http://dissem.in/r/7363/natalie-hershlag).

La recherche a fourni l'unique résultat suivant :
- [A Simple Method To Demonstrate the Enzymatic Production of Hydrogen from Sugar](http://pubs.acs.org/doi/abs/10.1021/ed075p1270)

Mais pas l'article suivant :
- [Frontal Lobe Activation during Object Permanence: Data from Near-Infrared Spectroscopy](http://www.sciencedirect.com/science/article/pii/S1053811902911705)

Je ne connaissais que le 2e (une excellente lecture que je vous recommande d'ailleurs), mais apparemment le premier est également d'elle, comme l'indique [cet article](http://patch.com/new-york/syosset/from-duckling-to-swan-syosset-remembers-natalie-portman), où vous apprendrez qu'elle a eu un score parfait à SAT.

**Comment by wetneb** [comment]
Je ferme parce que ça devrait être résolu par le nouveau backend (déjà couvert par d'autres issues)
