### ISSUE TITLE
Front page: move to standard search interface

### ISSUE THREAD

**Issue by sje30** [dissemin/dissemin#271]
How about allowing people to search by surname only?

search tool currently on front page requires forename and surname, but many names (like mine) are fairly unique.

**Comment by wetneb** [comment]
Already implemented in the new version, you can try it out here:
http://diego.dissem.in:8000/search/

**Comment by sje30** [comment]
Great.  

Although I can't get it to work just by typing in my surname - it still asks for first name. I tried the url above.

**Comment by sje30** [comment]
Also,  I think (for the lazy) you might need an example of a couple of names to search for.  Otherwise, if someone types in a name that doesn't yet have a profile, they have to wait a few minutes to start seeing results.

**Comment by wetneb** [comment]
Hum, I guess you're talking about the form on the front page. I was talking about the search form on the right-hand side of the search page. You can use it like this:
http://diego.dissem.in:8000/search/?q=&authors=eglen&pub_after=&pub_before=&reverse_order=&sort_by=&availability=

**Comment by sje30** [comment]
Also, perhaps the front page could have an example profile for

 "dissem.in OA hero of the week"

where you show the profile of a user with a high percentage of OA papers.

**Comment by wetneb** [comment]
Yeah! And I like your idea of badges too.

**Comment by a3nm** [comment]
Just my two cents, but I'm not sure about the "hero of the week" idea. First, users might dislike being cast in the spotlight like that, so you'd probably need their express agreement. Second, I'd say it gives the impression that we are more of a social thing, rather than infrastructure. Also note that Wikimedia and StackExchange projects don't have anything like this, AFAIK.

-- 
Antoine Amarilli

**Comment by a3nm** [comment]
Regarding the front page search form: I think it would be better to have
a single search field on the front page, à la Google, which could be
used to search for an author (with no need to separate first or last
name), paper title, or DOI (or even institution or publisher maybe?).

-- 
Antoine Amarilli

**Comment by wetneb** [comment]
Yes, this is what we're heading to I think.

**Comment by a3nm** [comment]
Another idea: when redesigning the front page to have a single search field, it would be great to play with the tab order such that the field has focus by default (and you don't need to tab multiple times to get to it).

Also, shouldn't the issue be reopened now that it talks about something that isn't already implemented on the beta?

**Comment by sje30** [comment]
hey yes, please re-open @wetneb -- several months later I still have to type in a forename even when my surname should be sufficient.

**Comment by wetneb** [comment]
@sje30: this is fixed in the new version, that should be rolled out some day. Can you try http://sandbox.dissem.in/ and tell me what you think? Paper availabilities will probably be wrong: that's normal.

**Comment by sje30** [comment]
ah, thanks, that looks better!
