### ISSUE TITLE
Test more the deposits interfaces by adding a dry_run flag

### ISSUE THREAD

**Issue by RaitoBezarius** [dissemin/dissemin#274]
Currently, we have more difficulty to test deposits interface than other parts of Dissemin mainly due to the fact we don't want to spam submit on Zenodo and SWORD repositories.

The solution to this problem is to add a `dry_run` flag for the interfaces which will make them submit nothing regardless of what we do.

Doing this will let us test freely the interfaces and increase further the code coverage! :tada:

**Comment by wetneb** [comment]
We should essentially use this to test metadata generation for many papers, and test it by sending the metadata to the servers, cancelling the deposit at the end of the process. This is possible for Zenodo at least (not sure about HAL or DSpace).

**Comment by wetneb** [comment]
This has been implemented in the `hal` branch.

**Comment by wetneb** [comment]
Merged.
