### ISSUE TITLE
Change 'available' to 'open access' ?

### ISSUE THREAD

**Issue by wetneb** [dissemin/dissemin#275]
We got a suggestion: changing 'available' (as in 'Available from the publisher', 'Available from the author') to 'open access', because 'available' is not clear enough. What do you think?

**Comment by a3nm** [comment]
I'd say "open access" is good for people who know what it means. For
people who have never heard the term "open access", I'm not sure it's
clearer.

You could replace "available" by "freely available", which I think
clears up any possible confusion; but then you don't have the "open
access" keyword which is arguably useful for people who know it.

So I don't really know what to think. :)

-- 
Antoine Amarilli

**Comment by nemobis** [comment]
Please don't use "freely available", the term "free" is confusing. "Available gratis" would be ok.

**Comment by a3nm** [comment]
I think "Available for free" is better than "Available gratis"

**Comment by wetneb** [comment]
Closing as no consensus was reached, feel free to reopen if this is still current.
