### ISSUE TITLE
Make Dissemin more PEP8 compliant

### ISSUE THREAD

**Issue by RaitoBezarius** [dissemin/dissemin#278]
`metadataFormatter` is not really PEP8 compliant

**Comment by wetneb** [comment]
what do you have against Camel case :-(

**Comment by RaitoBezarius** [comment]
> Modules should have short, all-lowercase names. Underscores can be used in the module name if it improves readability. Python packages should also have short, all-lowercase names, although the use of underscores is discouraged.

:smile:

**Comment by wetneb** [comment]
This specific example has been fixed :-)
