### ISSUE TITLE
When searching for a user, the link to the Orcid account should open in a new tab

### ISSUE THREAD

**Issue by a3nm** [dissemin/dissemin#280]
Steps to reproduce:
- Search for a user on the front page, e.g., "Antoine Amarilli"
- When the box pops up to ask "Looking for this researcher?", click on the Orcid link (because, e.g., you didn't see the "Yes" button).
- The link opens in the same tab and confusion ensues

I think the Orcid link, when clicked, should open in a new tab.

Also, I think the UI should encourage the user to click "Yes" more visibly. Maybe make the entire row clickable (with the same action as "Yes"?). Or make the Orcid link less visible somehow?

**Comment by wetneb** [comment]
What about simply dropping this interface and suggest ORCID profiles directly from the search results, when the user searches for a name that matches a profile?

**Comment by a3nm** [comment]
On Tue, Jul 05, 2016 at 01:29:12AM -0700, Antonin wrote:
> What about simply dropping this interface and suggest ORCID profiles
> directly from the search results, when the user searches for a name
> that matches a profile?

Sure, but then you'll probably still have the problem of users clicking
on the result because they want papers by this person, vs users clicking
on the ORCID link because they want to open the profile.

In any case, you can probably ignore my comment if you intended to
change this interface anyway!

-- 
Antoine Amarilli

**Comment by wetneb** [comment]
This has been solved by removing this dialog altogether.
