### ISSUE TITLE
Statistics: shorten numbers on the pie

### ISSUE THREAD

**Issue by wetneb** [dissemin/dissemin#281]
The numbers associated with each category should be shortened (1045 -> 1K, 4327940 -> 4.3M) to be more readable.

**Comment by RaitoBezarius** [comment]
@wetneb Do you have an example where an author has a ton of numbers in his statistics?

**Comment by wetneb** [comment]
It's not really about researchers, but bigger things such as
departments, institutions, publishers… I was actually thinking about the
statistics on the main page:
http://diego.dissem.in:8000/
