### ISSUE TITLE
Full text search or search a paper by his title would be handy

### ISSUE THREAD

**Issue by RaitoBezarius** [dissemin/dissemin#284]
When a new user goes on the front page of Dissemin, he might be interested into searching a paper.

We can easily find an author's papers, but if you know only the title of a paper, it is hard.

A full text search / anything would be handy.

**Comment by wetneb** [comment]
yeah we'll just replace the front page by a Google-like search interface, I think

**Comment by wetneb** [comment]
This field is already available from the search interface.
