### ISSUE TITLE
Ignore book chapters when they are part of a monograph

### ISSUE THREAD

**Issue by wetneb** [dissemin/dissemin#296]
Crosssref issues individual DOIs for book chapters. We want to keep these book chapters as individual papers when they are authored by different people (typically, papers in conference proceedings often show up as book chapters), but we want to remove book chapters coming from single-authored monographs. Otherwise they take up a lot of space in the publication lists of authors.

Proposed solution: reject papers from Crossref which are book-chapters and part of monographs (I think this is visible in the metadata).

**Comment by a3nm** [comment]
Related complaint: it seems that, in some cases, Dissemin is generating
separate publications for each *entry* of a reference work like the
Encyclopedia of Database Systems. See, e.g.,

http://dissem.in/p/14465/adaptive-interfaces
http://dissem.in/p/14466/adaptive-message-oriented-middleware
http://dissem.in/p/14468/adaptive-middleware-for-message-queuing-systems

(fortunately, I think it gave up at some point)

-- 
Antoine Amarilli

**Comment by wetneb** [comment]
@a3nm: should we ignore these document types? The examples you give are actually paywalled (and it's really ridiculous - Springer displays an "excerpt from the content" which is half the size of the actual content, and it's not even possible to buy access to it as far as I can tell).

What about simply changing the categories displayed by default in search views? We would only display, say, journal articles, conf. proceedings, preprints, tech reports, and any other category that "looks like an paper people could upload".

**Comment by wetneb** [comment]
@a3nm: actually, the examples you mention are marked as "book-chapter" in Crosssref… I don't see any way to distinguish between legit and non-legit "book-chapters". I don't think ignoring all book chapters is an option (for instance, some LNCS papers show up as book chapters: http://doi-cache.dissem.in/10.1007/978-3-642-21222-2_38).

Anyway, this will not be such a big issue in the new system where publications will not be automatically associated to profiles (so profiles will not be cluttered with rubbish entries). So I'm closing this issue, feel free to reopen it if you find any way to filter out spurious book chapters.

**Comment by a3nm** [comment]
I guess one way to tell that (some of) these entries are bogus is that
they appear on a single page of one book where other entries appear,
implying that they take up less than a single page.

Just for reference -- it's probably not worth it to implement this
heuristic. I agree that we can see in the new version.

-- 
Antoine Amarilli
