### ISSUE TITLE
use  dissemin/deposit/hal/ as API

### ISSUE THREAD

**Issue by monperrus** [dissemin/dissemin#312]
I try to use dissemin/deposit/hal/ as an API (from branch beta). However, I cannot load the modules, there is an exception.

Any idea to solve this?

```
from deposit.hal.metadata import AOFRFormatter
---------------------------------------------------------------------------
ImproperlyConfigured                      Traceback (most recent call last)
<ipython-input-2-049d7514ee1a> in <module>()
----> 1 from deposit.hal.metadata import AOFRFormatter

/tmp/dissemin/deposit/hal/metadata.py in <module>()
     30 from django.utils.translation import ugettext_lazy as _
     31 from lxml import etree
---> 32 from papers.models import Paper
     33 
     34 HAL_TOPIC_CHOICES = [

/tmp/dissemin/papers/models.py in <module>()
     56 from datetime import timedelta
     57 import re
---> 58 from statistics.models import AccessStatistics
     59 from statistics.models import combined_status_for_instance
     60 from statistics.models import STATUS_CHOICES_HELPTEXT

/tmp/dissemin/statistics/models.py in <module>()
    238 
    239 
--> 240 class AccessStatistics(models.Model, BareAccessStatistics):
    241     """
    242     Caches numbers of papers in different access statuses for some queryset

/tmp/dissemin/statistics/models.py in AccessStatistics()
    242     Caches numbers of papers in different access statuses for some queryset
    243     """
--> 244     num_oa = models.IntegerField(default=0)
    245     num_ok = models.IntegerField(default=0)
    246     num_couldbe = models.IntegerField(default=0)

/usr/lib/python3/dist-packages/django/db/models/fields/__init__.py in __init__(self, verbose_name, name, primary_key, max_length, unique, blank, null, db_index, rel, default, editable, serialize, unique_for_date, unique_for_month, unique_for_year, choices, help_text, db_column, db_tablespace, auto_created, validators, error_messages)
    164         self.db_index = db_index
    165         self.db_column = db_column
--> 166         self.db_tablespace = db_tablespace or settings.DEFAULT_INDEX_TABLESPACE
    167         self.auto_created = auto_created
    168 

/usr/lib/python3/dist-packages/django/conf/__init__.py in __getattr__(self, name)
     51     def __getattr__(self, name):
     52         if self._wrapped is empty:
---> 53             self._setup(name)
     54         return getattr(self._wrapped, name)
     55 

/usr/lib/python3/dist-packages/django/conf/__init__.py in _setup(self, name)
     37                 "You must either define the environment variable %s "
     38                 "or call settings.configure() before accessing settings."
---> 39                 % (desc, ENVIRONMENT_VARIABLE))
     40 
     41         self._wrapped = Settings(settings_module)

ImproperlyConfigured: Requested setting DEFAULT_INDEX_TABLESPACE, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.

```

**Comment by wetneb** [comment]
Hi! Are you using it within a Django project? Our interface relies on Django, so you should make sure Django is initialized properly in your context too.

By the way, we are currently working on this interface on other branches (hal and raito/hal). The current code needs quite a lot of cleaning. I'd be happy to know more about your own use case - it'd be great if we could work together on common issues!

**Comment by monperrus** [comment]
I want to use it as an API  on the command line . 

Is there a way to initialize django outside a webbapp? (the following fails)
```
from django.conf import settings
settings.configure()
AppRegistryNotReady: Apps aren't loaded yet.
```

**Comment by monperrus** [comment]
> By the way, we are currently working on this interface on other branches (hal and raito/hal)

Which branch should I look at first then?

**Comment by wetneb** [comment]
Currently hal and raito/hal mostly differ on the UI so if you're only interested in the depositing code, they will both work.

So, currently, to use the current code in a standalone way, I guess you should just copy the metadata-generating code (in `deposit.hal.metadata`) and maybe the SWORD interface (in `deposit.hal.protocol`) and adapt them to your own interface. Otherwise you are going to have a hard time getting rid of Django-related stuff. The metadata-generating code takes currently a `BarePaper` as input, plus informations input by the user from a Django form, so you would need to change these to your own metadata format.

If it's ok for you to have Django as a dependency, then you can follow these docs to init it manually:
https://docs.djangoproject.com/en/1.10/topics/settings/#calling-django-setup-is-required-for-standalone-django-usage

But we could also try to keep in mind that you're interested in this and try to make our own code more modular so that the HAL interface is better isolated.

**Comment by monperrus** [comment]
> If it's ok for you to have Django as a dependency, then you can follow these docs to init it manually:
https://docs.djangoproject.com/en/1.10/topics/settings/#calling-django-setup-is-required-for-standalone-django-usage

Thanks for your help.

Some progress:

```
import django
import os
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "dissemin.settings")
django.setup()
/usr/lib/python3/dist-packages/django/conf/__init__.py in __init__(self, settings_module)
    114 
    115         if not self.SECRET_KEY:
--> 116             raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
    117 
    118         if hasattr(time, 'tzset') and self.TIME_ZONE:

ImproperlyConfigured: The SECRET_KEY setting must not be empty.
```

What should be this SECRET_KEY?

**Comment by wetneb** [comment]
Any random-looking string. It's only used to generate tokens in the web UI.

**Comment by RaitoBezarius** [comment]
@monperrus You might be interested to use the Vagrant virtual machine to get you started faster in terms of dependencies :).

If you have any questions on the setup or why something is not working, don't hesitate to shoot us a message or open an issue!

**Comment by monperrus** [comment]
With some further config, I am able to create a paper as an API:

    In [44]: p = Paper.create_by_doi('10.1007/978-3-662-47666-6_5')
    In [45]: p
    Out[45]: <Paper: Provenance Circuits for Trees and Treelike Instances>
    
    formatter = AOFRFormatter()
    formatter.toString(p,'ff')

However, I have another problem, see #313

**Comment by monperrus** [comment]
To sum up, to use  dissemin/deposit/hal/ as API

1. set up Django deps `virtualenv .` and `pip install -r requirements.txt`
1. set up Django's Postgres' database (dissemin does not work with SQLite)
1. create `__init__.py` (`echo "from .dev import *" >> dissemin/settings/__init__.py`)
1. create `secret.py` (`cp dissemin/settings/secret_template.py dissemin/settings/secret.py`)
1. create `university.py` (`cp dissemin/settings/university_template.py dissemin/settings/university.py`)
1. disable test dependency to redis (`echo "CELERY_ALWAYS_EAGER = True" >> dissemin/settings/__init__.py`) (solution from #314)
