### ISSUE TITLE
make PrefilledTest independent of haystack

### ISSUE THREAD

**Issue by monperrus** [dissemin/dissemin#313]
I'm working on the HAL binding (see #312).
when running test `deposit.hal` (`python manage.py test deposit.hal`), it fails because PrefilledTest depends on haystack and a server at `http://localhost:9200/`.

In order to simplify installation and testing, is it possible to replace the dependency to a haystack server in PrefilledTest, and to replace it for instance by loading the data from disk directly?

**Comment by wetneb** [comment]
@monperrus: thanks, the dependency was spurious, so I removed it.
