### ISSUE TITLE
Impossible to log out and log back in as a different user

### ISSUE THREAD

**Issue by a3nm** [dissemin/dissemin#321]
If I log out of Dissemin, and then lock back in by clicking on "Log in" on http://dissem.in/accounts/login/?next=/ then I am automatically logged in as myself (without going via the ORCID website). That's very nice, but it would be problematic if I was trying to log in as someone else. I can solve this by manually deleting cookies, but the regular user cannot.

Is this intended behavior? If yes, what about adding a button "not [NAME]" at the top right to log out (and redirect to the login page) and really forget about the previous login? 

(EDIT: you need to clear the ORCID cookies, not the Dissemin ones, so maybe this is ORCID's fault. I don't know whether it can be remedied by calling something else to log out "for real" or log in "from scratch".)

**Comment by wetneb** [comment]
@a3nm: to log in as a different user, you would need to go to http://orcid.org/, logout there, and then login again from dissemin.
But it should be possible to log users out of ORCID when logging them out of dissemin. (At least I remember it's possible with CAS. Not sure about OAuth.)

**Comment by a3nm** [comment]
On Fri, Oct 14, 2016 at 04:04:58AM -0700, Antonin wrote:
> @a3nm: to log in as a different user, you would need to go to
> http://orcid.org/, logout there, and then login again from dissemin.

Nope, it doesn't seem to work: when I'm logged in Dissemin, I don't
appear as logged in on <https://orcid.org/signin>.

But in any case, this doesn't solve the issue, because it's not
discoverable by users.

> But it should be possible to log users out of ORCID when logging them
> out of dissemin. (At least I remember it's possible with CAS. Not sure
> about OAuth.)

OK, so if possible, it would be nice to do so. If not, I guess the issue
could also be reported to ORCID, and meanwhile the link "That's not me"
could at least show a tooltip with instructions about how to proceed.

-- 
Antoine Amarilli

**Comment by wetneb** [comment]
This is now implemented.
