### ISSUE TITLE
Add figshare interface

### ISSUE THREAD

**Issue by wetneb** [dissemin/dissemin#331]
Figshare would be a nice repository to have.
Pointers:
- https://docs.figshare.com/api/upload_example/
- http://dev.dissem.in/doc/repository_interfaces.html

**Comment by wetneb** [comment]
Note: we are not actually sure we want to have this interface.

**Comment by nemobis** [comment]
IMHO this can be declined, there is no good reason to use or advertise Figshare. If someone comes up with a use case that Zenodo and OSF don't cover, and that researchers looking for their own works to self-deposit would also need, this could be reopened.
