### ISSUE TITLE
Issue with affiliate_author_with orcid

### ISSUE THREAD

**Issue by wetneb** [dissemin/dissemin#332]
The same orcid id gets affected to multiple authors:
http://sandbox.dissem.in/r/6403/wenxin-niu

**Comment by wetneb** [comment]
http://sandbox.dissem.in/r/241820/alexander-bolshoy

**Comment by wetneb** [comment]
Not reproducible and probably fixed by a recent change in unify_name_lists.

**Comment by wetneb** [comment]
http://new.dissem.in/p/21591003/global-distribution-of-observed-climate-change-impacts

**Comment by wetneb** [comment]
This can be reproduced here:
https://dissem.in/p/94148147/juvenile-paget-disease
https://dissem.in/r/10749/stergios-polyzos

**Comment by a3nm** [comment]
In these two examples, the problem is caused by Crossref being wrong about the authors to which the ORCID should be associated.

**Comment by wetneb** [comment]
> Thank you for bringing this to our attention.  All Crossref metadata, including ORCID IDs, are supplied to us by the content's publisher.  Crossref doesn't make assertions or changes to publisher metadata directly.  Our system also doesn't have a way to query the ORCID ID and check that it matches the author name it's been submitted with.  So, just like a publisher can mistakenly send us the wrong page number or misspell an author's name or send in any other incorrect metadata, they can send us incorrect ORCIDs as well.
> 
> I can reach out to Springer-Nature - publisher of 10.1038/nclimate2529 - and to Elsevier - publisher of 10.1016/j.metabol.2017.10.007 - and pass along your concerns.  They can correct the ORCIDs by submitted updated metadata deposits to our system.  You may wish to contact the publishers directly as well, for the fastest possible response.
