### ISSUE TITLE
ORCID import failure for 0000-0002-9658-1473

### ISSUE THREAD

**Issue by wetneb** [dissemin/dissemin#334]
Importing 0000-0002-9658-1473 raises an exception when trying to affiliate author with ORCIDs.

**Comment by bhojarajug** [comment]
any update on this issue -

**Comment by wetneb** [comment]
@bhojarajug our new version has been deployed, the issue should be fixed.

**Comment by bhojarajug** [comment]
Hi

No still i am not seeing all records updated at Dissem (shows only 13 records) whereas in ORCID record shows 37.

Regards 
Bhojaraju
    
************************************************************************************************************

On Sat, Mar 4, 2017 at 2:58 PM, Antoine Amarilli <a3nm@a3nm.net> wrote:
 
Dear Bhojaraju,

Sorry for getting back in touch with you so late about the problem which
you reported in Dissemin, reproduced below.

We believe that the issue should now be solved. If you are still
encountering the problem, please feel free to reply to this email or to
comment on the Github issue.

Thanks again for your feedback!

Best regards,

--
Antoine Amarilli
