### ISSUE TITLE
Grabbing old papers from Journal of Neuroscience

### ISSUE THREAD

**Issue by sje30** [dissemin/dissemin#335]
Hi,

Papers published in Journal of Neuroscience should be freely available after 6 months.  e.g. here is an old one of mine on my profile page:

http://dissem.in/p/214508/developmental-loss-of-synchronous-spontaneous-activity-in-the-mouse-retina-is-independent-of-visual-experience

I can upload the file myself, but just wondering if there is anything more useful that can be done so that you get all J Neurosci papers without manual intervention?

Here is the paper:  http://www.jneurosci.org/content/23/7/2851.short

Thanks, Stephen

**Comment by wetneb** [comment]
I'm currently working on full text detection, which should solve this issue.

**Comment by sje30** [comment]
> I'm currently working on full text detection, which should solve this
> issue.

great.  would you recommend I upload my old J Neurosci papers now, or
hold off and then test later?

**Comment by wetneb** [comment]
As you want, we should be able to test independently anyway. Anyway you can't deposit via Dissemin right now because of https://github.com/zenodo/zenodo/issues/934 :-(

**Comment by sje30** [comment]
> As you want, we should be able to test independently anyway. Anyway you
> can't deposit via Dissemin right now because of zenodo/zenodo#934 :-(

good point!

**Comment by lnielsen** [comment]
@sje30 @wetneb This was due to a service outage of the storage cluster from 17:57-~20:20 yesterday.

**Comment by sje30** [comment]
thank you.  now uploaded!
