### ISSUE TITLE
Problems depositing paper

### ISSUE THREAD

**Issue by sje30** [dissemin/dissemin#336]
I'm trying to upload a paper for : http://dissem.in/deposit_paper/214561/

but after uploading the PDF to your site and then adding the abstract and selecting abstract, when hitting the magic "Deposit" button I see:

    Unable to authenticate to Zenodo.

what's up?  zenodo.org is up right now.

**Comment by wetneb** [comment]
Thanks for reporting. Zenodo's API is down on our side (HTTP error 504). I will report that to them.

**Comment by sje30** [comment]
thanks.  Zenodo upload working again.
