### ISSUE TITLE
Help with upload - automatic extraction of abstract?

### ISSUE THREAD

**Issue by sje30** [dissemin/dissemin#337]
Hi,
When I upload a paper, I am then asked to upload the abstract of the paper.  This is not quite straightforward -- in my case, I go back to the .tex file normally and make an ascii version w/out tex commands.

Have you tried automatic extraction of the abstract, e.g. using soemthing like: http://labs.crossref.org/pdfextract/

This is the kind of thing that paperpile (paperpile.com) does so smoothly...

**Comment by wetneb** [comment]
We do try to extract the abstract, but from the publisher's landing page. Extracting it from the PDF is also an option, you're right. It seems a bit heavier but would be worth trying.

**Comment by sje30** [comment]
Great.  Anything you can do to minimise the work done in upload will increase the number of uploads.

**Comment by wetneb** [comment]
This has been fixed (Zotero is back up).
