### ISSUE TITLE
API?

### ISSUE THREAD

**Issue by sje30** [dissemin/dissemin#339]
Do you have an API for interacting with your system?  e.g. I would like to give you an ORCID and get, in return, some useful information back, e.g. how many papers are available, or the "badge" for a given user.

**Comment by wetneb** [comment]
the API ( http://dev.dissem.in/api.html) only covers individual papers for now. But that's a very sensible feature request!

**Comment by sje30** [comment]
> the API ( http://dev.dissem.in/api.html) only covers individual papers
> for now. But that's a very sensible feature request!

Great.  The kind of thing I'm thinking of is to build up a web page
(rebuilt every night) where for each PI in the dept, we have a picture
of their "badge" (the four coloured segments) , and then clicking in
their badge takes you to their dissem.in page.

**Comment by sje30** [comment]
I like that you added "easy" tage to the request.  Is it really easy?  I now have a hand-edited list of 20 ORCIDs from PIs in my department, and would like to see how easy I could then link to their dissem.in profile (or even just PNG of their pie chart/badge).

**Comment by wetneb** [comment]
You can link to http://dissem.in/$orcid where $orcid is the orcid
identifier of the researcher.

**Comment by sje30** [comment]
wonderful, thank you!

I assume the first time I visit an orcid page (i.e. a cold URL that
no-one has visited before), your system will need to spend e.g. a minute
collating the information, but then on subsequent visits to the same
URL, it will be warm and therefore the page will render pretty fast?

(That at least is what I am guessing...!)

Stephen

**Comment by wetneb** [comment]
Exactly!
And, in the new version, the first hit on the URL will be immediate just like the others.

**Comment by sje30** [comment]
Thanks to @lgatt0 with the following hint to check the source.  We can get a long way in R thanks to some cool packages:

```
require(V8)
require(httr)
##a = GET("http://dissem.in/r/7683/stephen-eglen")
a = GET("http://dissem.in/0000-0001-8607-8025")
o = content(a, "text")
p = strsplit(o, split="\n")
x = grep("var data", p[[1]])
##p[[1]][x]

## Start up the javascript engine.
ct = v8()
ct$eval(p[[1]][x])
output = ct$get("data")

detailed = output$detailed
ids = detailed$id
values = detailed$value
data.frame(ids,values)
```

generates

```
      ids values
1      oa     21
2      ok     29
3 couldbe      8
4     unk     10
5  closed      0
```
