### ISSUE TITLE
wrongly assigned publications

### ISSUE THREAD

**Issue by sgibb** [dissemin/dissemin#340]
Among my publications there is one I am not authored at all. Please see 
http://dissem.in/p/215647/a-draft-map-of-the-mouse-pluripotent-stem-cell-spatial-proteome where *Thomas Naake* was wrongly linked to my profile: http://dissem.in/r/9209/sebastian-gibb

Is there a way to remove wrongly assigned records?

**Comment by wetneb** [comment]
Only publications linked to your ORCID profile will be included in your public profile in the new version, which should solve the issue.

**Comment by wetneb** [comment]
this is solved by the new version.
