### ISSUE TITLE
Minor Grammar Issue

### ISSUE THREAD

**Issue by rossmounce** [dissemin/dissemin#343]
It should say "Show more information" not "Show more informations"
![2017-01-31-230029_1366x744_scrot](https://cloud.githubusercontent.com/assets/824120/22488357/770ac0de-e809-11e6-9d13-07dfb5d14726.png)

Dissemin looks really cool, lovely UI. I will have a play with my profile and see if I have anything else to report back.

**Comment by wetneb** [comment]
@rossmounce Thanks! yeah this dialog is quite ill phrased.

**Comment by a3nm** [comment]
Please note that this has only been fixed in the beta branch, so it will only go live when we deploy the new version. Thanks again for reporting and sorry for the delay in fixing this!
