### ISSUE TITLE
ORCID interface misses many papers [$25]

### ISSUE THREAD

**Issue by pboesu** [dissemin/dissemin#344]
Hi,

I'm having trouble getting two of my publications recognized from my ORCID profile. Both papers have DOIs, and are from the same publisher ["Inter Research"](www.int-res.com)

![screen shot 2017-01-31 at 6 02 55 pm](https://cloud.githubusercontent.com/assets/9256856/22488377/aa8e24d4-e7df-11e6-9312-384674191adc.png)

My ORCID is [0000-0001-6723-6833](http://orcid.org/0000-0001-6723-6833) and the offending DOIs are 

http://doi.org/10.3354/meps11675
http://doi.org/10.3354/meps09890

**Comment by wetneb** [comment]
Thanks, I'll look into that!

**Comment by wetneb** [comment]
So, this issue is for all the papers that are ignored by our ORCID interface, be they reported as ignored or not. The bounty will go to any effort to significantly reduce this issue. (There will always be cases where we don't have enough metadata to import the papers.)
