### ISSUE TITLE
Refining a search shouldn't trigger any requests

### ISSUE THREAD

**Issue by a3nm** [dissemin/dissemin#355]
When refining a search (e.g., filtering by date, selecting a subset of document types, etc.), the change should be applied immediately (i.e., by doing it client-side), rather than triggering a request and having a noticeable delay. The same applies when clicking, e.g., "Available from the author" under the pie chart.

**Comment by a3nm** [comment]
@RaitoBezarius : I don't think this is a documentation issue. :)

**Comment by RaitoBezarius** [comment]
Definitely, this was a bot sorry!

**Comment by Phyks** [comment]
Hi,

Given the number of open issues we have to work on, I'd rather close this one as it is quite a moonshot and I think this is not easy to do with the current search mechanism. Feel free to reopen if I'm mistaking :)
