### ISSUE TITLE
More explicit error message when paper is already in HAL [$10]

### ISSUE THREAD

**Issue by wetneb** [dissemin/dissemin#356]
Deposit record: 515 (in prod)
We shouldn't just say "HAL refused the deposit (HTTP error 400)" but explain that the paper is already in HAL.

This should be solved by modifying the code that submits the deposit to HAL:
https://github.com/dissemin/dissemin/blob/master/deposit/hal/protocol.py

**Comment by Phyks** [comment]
I was thinking about filtering on the HTTP error code to change the message, but I think 400 is a much more general error than just "the paper is already in HAL". In SWORD doc:

> 12.1.3. sword:ErrorBadRequest
> 
> Some parameters sent with the POST were not understood. The server MUST also return a status code of 400 Bad Request. 

It seems SWORD interface should return an XML error document, which should be more specific and we could match against. How can I reproduce the failed deposit to get such an error response?

Or did I missed something and for HAL, `400` error code in this context always mean "the paper already exists"?

**Comment by wetneb** [comment]
No you're right, the 400 error code is quite generic. Here is an example of the payload you get back:
```
<?xml version="1.0" encoding="utf-8"?>
<sword:error xmlns:sword="http://purl.org/net/sword/error/" xmlns="http://www.w3.org/2005/Atom" href="http://purl.org/net/sword/error/ErrorBadRequest">
  <title>ERROR</title>
  <updated>2017-03-03T16:07:53+01:00</updated>
  <author>
    <name>HAL SWORD API Server</name>
  </author>
  <source>
    <generator uri="https://api.archives-ouvertes.fr/sword" version="1.0">hal@ccsd.cnrs.fr</generator>
  </source>
  <summary>Some parameters sent with the request were not understood</summary>
  <sword:treatment>processing failed</sword:treatment>
  <sword:verboseDescription>{"duplicate-entry":{"hal-01321239":{"doi":"1.0"}}}</sword:verboseDescription>
  <link rel="alternate" href="https://api.archives-ouvertes.fr" type="text/html"/>
</sword:error>
```
