### ISSUE TITLE
Dead link in FAQ

### ISSUE THREAD

**Issue by a3nm** [dissemin/dissemin#360]
In http://dissem.in/faq#oai the link is dead (the anchor doesn't work).

**Comment by Phyks** [comment]
* https://github.com/dissemin/dissemin/blob/db1a61db91cfa4a1c658c86108b09349df150c51/templates/dissemin/faq.html#L160 (useless `#team` and wrong link in French translation)
* https://github.com/dissemin/dissemin/blob/db1a61db91cfa4a1c658c86108b09349df150c51/templates/dissemin/faq.html#L386 (dead link)

as well :)
