### ISSUE TITLE
Issues with accents in the ORCID interface [$10]

### ISSUE THREAD

**Issue by wetneb** [dissemin/dissemin#362]
The accents are enclosed by brackets, they should not be:
http://dissem.in/r/9680/adria-martin-mor

**Comment by Phyks** [comment]
Problem seems to be that bibtexparser version in use is quite old. Provided that a new version is published, we could get rid of [this](https://github.com/dissemin/dissemin/blob/db1a61db91cfa4a1c658c86108b09349df150c51/papers/bibtex.py#L58-L67) (thanks to https://github.com/sciunto-org/python-bibtexparser/pull/64).

By re-enabling the `parser` kwarg (not sure why it was dropped in the first place) [here](https://github.com/dissemin/dissemin/blob/db1a61db91cfa4a1c658c86108b09349df150c51/papers/bibtex.py#L40), everything should be working fine.

I contacter sciunto to ask him about the publication of a new Bibtexparser version.

**Comment by wetneb** [comment]
@Phyks Great! In the meantime we can surely point to a particular git commit in requirements.txt, if the release on PyPI is not coming soon.

**Comment by wetneb** [comment]
@Phyks I can see you have been working on bibtexparser, that's awesome! Do you think a release is coming up soon or should we switch to a particular commit? (Any suggestions of a nice stable commit?)
