### ISSUE TITLE
Add translations to repository descriptions [$10]

### ISSUE THREAD

**Issue by wetneb** [dissemin/dissemin#364]
The descriptions for repositories are stored in the model (as fields of the Repository model). This makes it harder to translate them using standard i18n localization tools. We need to find another way to translate that. I remember seeing some Django add-ons for this kind of use case: we could use that or devise our own solution.

**Comment by beckstefan** [comment]
In #763 we introduced django-vinaigrette that does not use database for translation.

After gathering some experience, this should be applied to the description of repositories.

(And we can remove the bounty, I think.)
