### ISSUE TITLE
Depositing the full text of a paper on Zenodo disables the possibility to also deposit it on HAL

### ISSUE THREAD

**Issue by PLMir** [dissemin/dissemin#380]
When a paper is deposited in its full text version (on Zenodo?), it seems to become impossible to deposit it on another repository or in another version (such as preprint or postprint). 

An example of this issue can be encoutered here: http://dissem.in/p/92163417/coherent-structure-extraction-in-turbulent-channel-flow-using-boundary-adapted-wavelets

**Comment by wetneb** [comment]
This is because the paper is already both in Zenodo and HAL (see the links on the right hand side).
