### ISSUE TITLE
Some papers that have been deposited on Zenodo do not appear as such on dissemin

### ISSUE THREAD

**Issue by PLMir** [dissemin/dissemin#381]
This paper (https://zenodo.org/record/49380#.WObYFxLyhcw) was uploaded on Zenodo in May 2016. Dissemin, however, is not aware that this uploaded version exists and describes the full text as unavailable (http://dissem.in/p/151681/coherent-structures-in-the-boundary-and-cloud-layers-role-of-updrafts-subsiding-shells-and-environmental-subsidence).

**Comment by wetneb** [comment]
Solved by the oaDOI ingestion.
