### ISSUE TITLE
Some of the articles detected by dissemin are gibberish / non-existent 

### ISSUE THREAD

**Issue by PLMir** [dissemin/dissemin#384]
For instance, this article (http://dissem.in/p/4770/turbulence-using-orthogonal-wavelets-by) is titled "turbulence using orthogonal wavelets By". A search in Google Scholar finds no match for that title / article.

**Comment by nemobis** [comment]
This specific example was deleted; there are [other issues open with regard to specific importers](https://github.com/dissemin/dissemin/labels/fulltext%20availability). I suppose the most likely source of this record was BASE.
