### ISSUE TITLE
Increase in papers not found (404) via API?

### ISSUE THREAD

**Issue by eocarragain** [dissemin/dissemin#388]
I had written a script against the old version of the API where the doi was POSTED to http://dissem.in/api/query. Comparing results from this script with one modified to work against the newer GET api (i.e. http://dissem.in/api/10.1016/j.paid.2009.02.013), I get a "could not be found" response much more often: 

`{"message": "The paper you requested could not be found.", "error": 404}`

For example, this works and correctly classifies the item as Open Access:
`curl -d '{"doi":"10.1038/ncomms14774"}' http://dissem.in/api/query`

However, this returns the "could not be found" message:
`curl http://dissem.in/api/10.1038/ncomms14774`

For a batch of 352 2017 DOIs, the difference when running against the different API versions is as follows:

Response | POST | GET
----------- | ------ | ---
404 | 10 | 306
NOK | 8 | 1
OA | 62 | 0
OK | 265 | 14
UNK	 | 7 | 31

Over a larger batch of ~14K records, Post yielded only about 200 404s, whereas Get yielded over 4000 404s.

What is the difference between the two versions of the API? The new get version is great at identifying researchgate articles etc., but is the coverage less than before?

**Comment by wetneb** [comment]
@eocarragain Thanks a lot for this feedback. Yes we are aware of problems with this new version and I'd love to find the time to work to solve them. In the meantime you can still use the old version at old.dissem.in. Many apologies for that!

**Comment by eocarragain** [comment]
Thanks very much @wetneb,
Just a minor update to the example above: I accessed one of the author's ORCID pages on dissem.in: dissem.in/0000-0003-3915-2135 which fetched all his articles including the one above. As a result the get request now works as expected. Let me know if want me to provide other examples which still illustrate the issue.

Re using the old version, is there a difference between posting to old.dissem.in/api/query and simply dissem.in/api/query (which also seems to work)? For now, I think I'll take the approach of trying the new version first (since it has the extra researchgate information etc), and then falling back on posting to dissem.in/api/query when I get a 404 message?

Many thanks!

**Comment by nemobis** [comment]
> For now, I think I'll take the approach of trying the new version first (since it has the extra researchgate information etc), and then falling back on posting to dissem.in/api/query when I get a 404 message?

I'm doing the opposite, I use the POST version whenever possible and use the GET API when needed (e.g. to query for PDF URL). I don't know what's the better way...

**Comment by wetneb** [comment]
Hmm, it's not clear to me either! If the DOI metadata is slightly different from the metadata you are POSTing, the results might be different, and it's hard to know if one will be better than the other.

**Comment by a3nm** [comment]
Here is another example of a paper which exists on Zenodo but which Dissemin does not seem to be aware of: https://zenodo.org/record/439017 (not visible on https://dissem.in/search/?page=2&authors=St%C3%A9phane+Mottin).

**Comment by a3nm** [comment]
Another case: the paper https://api.crossref.org/v1/works/http://dx.doi.org/10.1108/jgm-05-2016-0020 does not seem to appear when searching for "Frithjof Arp" in Dissemin.

**Comment by wetneb** [comment]
Migrating all fulltext availability errors to #602 for clarity.
