### ISSUE TITLE
HAL affiliation autocomplete should group the proposed completions

### ISSUE THREAD

**Issue by a3nm** [dissemin/dissemin#390]
Completions should be grouped depending on the status of the affiliation (the AURéHAL color code), and possibly on the type of the affiliation, by grouping them in the suggestion list (à la "optgroup").

**Comment by Phyks** [comment]
Hasn't this been done in https://github.com/dissemin/dissemin/issues/741?

Otherwise, this issue could probably use more details as I probably misunderstood it :)

**Comment by a3nm** [comment]
Oops, good catch! Looks like I had forgotten about this issue when opening #741. Yes, this has been solved. Thanks!
