### ISSUE TITLE
DUMAS x dissem.in

### ISSUE THREAD

**Issue by jibe-b** [dissemin/dissemin#391]
Are [DUMAS](https://dumas.ccsd.cnrs.fr/) (an open archive specialized in Master thesis) and dissemi.in connected ?

Infos about DUMAS: http://opendoar.org/find.php/tools/FEUP?rID=1397&format=full

**Comment by wetneb** [comment]
@jibe-b DUMAS does not seem to be harvested by BASE, so no. Feel free to suggest that to them! :)
