### ISSUE TITLE
Some DOIs are not fetched from arXiv

### ISSUE THREAD

**Issue by Phyks** [dissemin/dissemin#392]
Hi,

arXiv repo enables users to put a DOI for their deposited paper, and it then eases a lot deduplication, as articles with the same DOI can be deduplicated efficiently. I think Dissemin already implements this.

However, it seems the DOI is not fetched for some papers. Consider http://dissem.in/p/5487785/implementation-of-low-loss-superinductances-for-quantum-circuits, it does not have any associated DOI (even though the arXiv deposited paper does have one). http://dissem.in/p/44182172/microwave-characterization-of-josephson-junction-arrays-implementing-a-low-loss-superinductance is the published version, and does have a DOI.

As the title differ quite a lot (I guess), the deduplication is not done on these papers. With the DOI, the title not matching would not be an issue :)

**Comment by Phyks** [comment]
Looking into it more in depth, [BASE OAI record](http://oai.base-search.net/oai?verb=GetRecord&metadataPrefix=base_dc&identifier=ftarxivpreprints:oai:arXiv.org:1206.2964) does not have the DOI information. So of course, Dissemin cannot retrieve it.

But [arXiv OAI record](http://export.arxiv.org/oai2?verb=GetRecord&identifier=oai:arXiv.org:1206.2964&metadataPrefix=oai_dc) does have the DOI exported. So this issue lies between BASE and arXiv. :/

**Comment by Phyks** [comment]
Closing as not a Dissemin issue. Will try to report to BASE.

**Comment by a3nm** [comment]
This has been reported to BASE.

**Comment by Phyks** [comment]
Answer from BASE:

> the answer is simple: BASE does not currently stored DOIs in its index at all. But here are working on it.

**Comment by wetneb** [comment]
@Phyks: well we do get plenty of arXiv DOIs from BASE… Even if they do not index them they do expose all the data they get from arXiv. It really looks like a problem with the incremental harvesting of updated records.
