### ISSUE TITLE
Better metadata for search engines - Dissemin is not indexed properly

### ISSUE THREAD

**Issue by wetneb** [dissemin/dissemin#393]
When you Google for "dissemin", you get: "dissem.in is currently in public beta. Please, let us know about any issue you might have, either on Github or by email at bugs@dissem.in."
That's not ideal!

**Comment by RaitoBezarius** [comment]
Whereas [DuckDuckGo](https://duckduckgo.com/?q=dissemin&ia=software) figures out the good metadata:

> Welcome to dissemin. Dissemin detects papers behind pay-walls and invites their authors to upload them in one click to an open repository.

:D.

**Comment by a3nm** [comment]
Shouldn't we simply remove this message from the home page? Dissemin has
been around for a while now, it's not perfect, but having the message
doesn't make it better :) maybe it elicits feedback but we already
receive lots of feedback relative to the time that we have to implement
it...

What do you think?

-- 
Antoine Amarilli

**Comment by wetneb** [comment]
@a3nm yeah that makes a lot of sense…

**Comment by a3nm** [comment]
I removed the banner. If anyone wants to add it back (or to add back something similar to that banner), please let me know. :)
