### ISSUE TITLE
[Hackathon] Idea: improve tests

### ISSUE THREAD

**Issue by jibe-b** [dissemin/dissemin#397]
May I ask for information about the tests that are lacking?

I'd offer to work on improving the test suite. It will help me get used to the code. And there are feature I'd like to add to dissem.in and I'd like to start with tests before implementation.

**Comment by wetneb** [comment]
One good place to find where tests are missing is via code coverage:
https://www.codacy.com/app/dissemin/dissemin/files?bid=5035065&filters=W3siaWQiOiJjb2x1bW5JbmRleCIsInZhbHVlcyI6WzVdfSx7ImlkIjoic29ydE9yZGVyIiwidmFsdWVzIjpbIkFzY2VuZGluZyJdfSx7ImlkIjoic2VhcmNoVGV4dCIsInZhbHVlcyI6W251bGxdfV0=

**Comment by wetneb** [comment]
(closing as not specific… but yes of course new tests are very welcome)
