### ISSUE TITLE
[suggestion] use a OA boosting doi resolver

### ISSUE THREAD

**Issue by jibe-b** [dissemin/dissemin#418]
When accessing the notice of a paper, a links points to doi.org to resolve the DOI.

![page-shot-2017-7-14 information extraction from bibliography for marker assisted selection in wheat - dissemin](https://user-images.githubusercontent.com/6146483/28222076-2e094ca0-68c6-11e7-830c-223a5ffcf209.png)

In the config file, the DOI resolver could be set to one that boosts OpenAccess, such as oadoi.org or any other.

Note: would this perturbate the DOI caching? As then, links to full-texts will no longer be added to the DOI cache.

**Comment by wetneb** [comment]
The point of these DOI links is that they should point to the publisher's version: we already provide links to alternative versions below. So I think that would be quite confusing for the user.

**Comment by jibe-b** [comment]
Thanks, that clarifies the reason of this link.

**Comment by wetneb** [comment]
@jibe-b if you want to add a link in the tools section I think that would be perfectly appropriate!

**Comment by jibe-b** [comment]
:+1: coming soon
