### ISSUE TITLE
False negatives for PubMed

### ISSUE THREAD

**Issue by nemobis** [dissemin/dissemin#433]
I assume you know you're missing some PubMed papers (oaDOI seems to do a separate lookup for them), but I'm opening this just to note down some examples.

https://dissem.in/p/87709904/rna-binding-proteins-and-the-genesis-of-neurodegenerative-diseases / https://doi.org/10.1007/978-3-319-08927-0_3 is reported as closed but is actually open at http://www.ncbi.nlm.nih.gov/pmc/articles/PMC4694570

**Comment by wetneb** [comment]
Yes, there is an issue with Pubmed's OAI feed (some records don't have any URLs), we have not set up any dedicated strategy to circumvent that.

**Comment by wetneb** [comment]
This was fixed thanks to oaDOI
