### ISSUE TITLE
False negative from tp.revistas.csic.es/repositorio.unican.es

### ISSUE THREAD

**Issue by nemobis** [dissemin/dissemin#436]
https://dissem.in/p/13589028/ is marked unavailable but the linked https://repositorio.unican.es/xmlui/handle/10902/2300 actually provides full-text; oaDOI redirects to http://tp.revistas.csic.es/index.php/tp/article/view/565/585 (gold OA journal it seems).

https://dissem.in/p/13589031/ is available at https://repositorio.unican.es/xmlui/handle/10902/2303

**Comment by wetneb** [comment]
Migrating all fulltext availability errors to #602 for clarity.
