### ISSUE TITLE
False negative from dspace records with citation_pdf_url meta tag

### ISSUE THREAD

**Issue by nemobis** [dissemin/dissemin#438]
The PDF for https://dissem.in/p/6812893/ is available at https://sdsu-dspace.calstate.edu/handle/10211.3/142438

Others:
* http://api.oadoi.org/10.1080/01615440.2015.1007194 is available at  http://hdl.handle.net/2299/16184  (`<meta content="http://uhra.herts.ac.uk/bitstream/2299/16184/3/Irish_Surnames_in_London_2014_repositoryVersion.pdf" name="citation_pdf_url">`)

**Comment by wetneb** [comment]
For the first paper, this cannot be solved via oaDOI because dissemin is not aware of any doi for that paper.
For the second paper, this should be solved once we query oaDOI's API (but that particular record was not in the dump we have ingested).

**Comment by wetneb** [comment]
Migrating all fulltext availability errors to #602 for clarity.
