### ISSUE TITLE
False negative from EPrints records with eprints.document_url meta tag

### ISSUE THREAD

**Issue by nemobis** [dissemin/dissemin#439]
https://dissem.in/10.1080/1461670x.2012.680810 is marked as not available but https://kar.kent.ac.uk/34500/ has the PDF. It's not currently indexed in BASE (https://www.base-search.net/Record/1e495be723cdb5a42957f7a18039f1932a5d587a28e4b2b1b5afc9031e1ef5c6/ ) and doesn't follow the Google Scholar format but the HTML has a meta tag:
```
<meta name="eprints.document_url" content="http://kar.kent.ac.uk/34500/1/Excellent%20but%20Gullible%20People%20FINAL2.doc.pdf" />
```
which might be common to all EPrints 3.3.15 installations.

I could not find the OAI-PMH URL to verify whether any dc:rights tag is included for this record as recommended by https://www.base-search.net/about/en/faq.php

**Comment by nemobis** [comment]
Ok, I think this is addressed by oaDOI API v2, for instance http://api.oadoi.org/10.1016/j.epsl.2014.08.029 has `      "free_fulltext_url": "http://authors.library.caltech.edu/50049/",`
while https://www.base-search.net/Search/Results?q=dccoll:ftcaltechauth&refid=dctableen doesn't find a single OA PDF for the repository (which is using EPrints 3.3.10).

I don't know whether this makes it redundant for your crawling interests.

**Comment by wetneb** [comment]
Migrating all fulltext availability errors to #602 for clarity.
