### ISSUE TITLE
Policy false negative for Latin American Antiquity

### ISSUE THREAD

**Issue by nemobis** [dissemin/dissemin#440]
https://dissem.in/p/58254349/central-america-a-natural-and-cultural-history says no policy known, but there is http://www.sherpa.ac.uk/romeo/issn/1045-6635/ (https://www.cambridge.org/core/services/open-access-policies/open-access-journals/green-open-access-policy-for-journals ). Updated on March 2017, could it be a cache issue?

**Comment by Phyks** [comment]
Likely to be solved by ongoing work on ROMEO (#623 #614).

**Comment by wetneb** [comment]
Thanks - that's a test case I had not thought about. Will write a unit test for this.

**Comment by wetneb** [comment]
I have started to recompute the publishers and availability statuses, which should solve this in the coming days.
