### ISSUE TITLE
HAL linked both with HTTP and HTTPS

### ISSUE THREAD

**Issue by nemobis** [dissemin/dissemin#447]
On https://dissem.in/p/6980066/ I see https://hal.archives-ouvertes.fr/hal-00983250 and http://hal.archives-ouvertes.fr/hal-00863293 . No duplicate here, but it would still be better to have a canonical protocol (HTTPS ideally).

**Comment by wetneb** [comment]
I don't see any clean way to do this, in general we would need to maintain a list of websites that are known to support HTTPS and upgrate HTTP to HTTPS for them… that does not sound feasible. Reopen if you see any better solution!
