### ISSUE TITLE
ResearchGate DOI deposited without DOI

### ISSUE THREAD

**Issue by nemobis** [dissemin/dissemin#449]
https://dissem.in/p/82831276/ links http://dx.doi.org/10.13140/RG.2.2.36205.38883 but was uploaded to https://zenodo.org/record/883624 without a DOI, so Zenodo assigned a new one:  http://doi.org/10.5281/zenodo.883624

This could be considered a feature, rather than a bug (the Zenodo DOI seems "more valuable" to me than the original), but I'm not sure it's intended.

**Comment by RaitoBezarius** [comment]
Basically, the expected behavior here is to have another "DOI" field with the Zenodo's DOI, right?
That sounds fair and reasonable to me.

**Comment by wetneb** [comment]
Basically we only transfer the DOI when it comes from CrossRef (which generally means it is the DOI of a published paper). DOIs from DataCite (such as the ones from Zenodo, ResearchGate, and others) are not transferred as they do not correspond to a publication. So, this behaviour is intended, closing this issue. Feel free to reopen this issue to change this.
