### ISSUE TITLE
Non-existing or superseded Springer DOI

### ISSUE THREAD

**Issue by nemobis** [dissemin/dissemin#450]
https://dissem.in/p/91632898/management-of-the-various-causes-of-thyrotoxicosis links https://doi.org/10.1385/1-59259-352-6:177 which leads to an error page; Google Scholar finds https://link.springer.com/chapter/10.1007/978-1-59259-352-1_9 (neither https://doi.org/10.1007/978-1-59259-352-1 nor https://doi.org/10.1007/978-1-59259-352-1_9 resolve).

**Comment by wetneb** [comment]
AFAICT this is just Springer's fault. Crossref still has metadata for this DOI: https://api.crossref.org/v1/works/http://dx.doi.org/10.1385/1-59259-352-6:177 so dissemin will keep importing it even if we remove it manually. They should get their **** together but I am clearly not going to bother reporting that.
