### ISSUE TITLE
False negative for a paper in HAL

### ISSUE THREAD

**Issue by nemobis** [dissemin/dissemin#451]
https://dissem.in/p/42124318/ says not available for https://doi.org/10.3758/s13414-012-0405-x but Google Scholar finds https://hal-amu.archives-ouvertes.fr/hal-01519759/

Might be just a matter of cache because the file was deposited "only" ~24 days ago:
> Soumis le : mardi 9 mai 2017 - 11:36:53
> Dernière modification le : mardi 4 juillet 2017 - 11:25:16
> Document(s) archivé(s) le : jeudi 10 août 2017 - 12:47:59

(If so, please close and merge to the other task about cache.)

**Comment by monperrus** [comment]
maybe because of https://github.com/CCSDForge/HAL/issues/8 (OAI-PMH interface of HAL not giving appropriate dc:rights)

**Comment by wetneb** [comment]
still not solved by oaDOI as this was not in the dump they provided us

**Comment by monperrus** [comment]
the fix for https://github.com/CCSDForge/HAL/issues/8 is not yet in production, but will arrive (thanks to @lfarhi)

**Comment by nemobis** [comment]
Now oaDOI resolves to the publisher's own OA PDF, but http://api.oadoi.org/v2/10.3758/s13414-012-0405-x knows about HAL. Dissemin still doesn't. Do we need a new dump from oaDOI?

**Comment by wetneb** [comment]
yes, or crawling their API directly as they advised us

**Comment by nemobis** [comment]
Martin Monperrus, 16/09/2018 15:18:
> This is not what you do already?

Most of the data on Dissemin comes from other crawlers, like 
oaDOI/Unpaywall and BASE.

**Comment by monperrus** [comment]
Then, my question is actually #536

**Comment by wetneb** [comment]
Migrating all fulltext availability errors to #602 for clarity.
