### ISSUE TITLE
Paper not found despite being available with same DOI

### ISSUE THREAD

**Issue by nemobis** [dissemin/dissemin#452]
https://dissem.in/10.1016/j.fodchem.2004.08.002 gives not found; but <https://dissem.in/p/49710495/esr-spectroscopic-study-reveals-higher-free-radical-quenching-potential-in-kodo-millet-compared-to-other-millets> is the same paper and has the same DOI correctly registered.

**Comment by wetneb** [comment]
The DOI in the first URL is different from the DOI in the second (the first one is missing an "o" in "fodchem").
