### ISSUE TITLE
False positive for Museum National d'Histoire Naturelle Paris

### ISSUE THREAD

**Issue by nemobis** [dissemin/dissemin#453]
https://dissem.in/p/93532570/the-anatomy-and-phylogenetic-affinities-ofcynthiacetus-peruvianus-a-largedorudon-like-basilosaurid-cetacea-mammalia-from-the-late-eocene-of-peru is marked as open access but http://www.bioone.org/doi/10.5252/g2017n1a1  requires login.

**Comment by wetneb** [comment]
Currently we don't have a way to downgrade individual papers - however we can flag the publisher as being not open access.

**Comment by wetneb** [comment]
Migrating all fulltext availability errors to #602 for clarity.
