### ISSUE TITLE
Depositing fails when disallowing third-party javascript

### ISSUE THREAD

**Issue by a3nm** [dissemin/dissemin#454]
When using uMatrix to block third-party javascript, depositing silently fails (the "processing" animation stays indefinitely), because of a dependency on cdnjs.cloudflare.com. Ideally, we could remove this dependency, or at least detect when third-party JS is blocked and display an explicit error.

(Edit: not sure whether this really prevented the deposit for completing; it's very slow, so maybe I wasn't patient enough. Anyway, it would still be good to remove this dependency if appropriate.)

**Comment by wetneb** [comment]
We have the following scripts:
* https://cdnjs.cloudflare.com/ajax/libs/fetch/1.0.0/fetch.min.js
* https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML
* https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.5/d3.min.js

I had looked into self-hosting mathjax but I think it was quite complicated - @a3nm I think you have some experience in that? The others should be easier to migrate - they are probably just included by third-party django libraries.

**Comment by Phyks** [comment]
I added some doc in https://github.com/dissemin/dissemin/pull/598 about self-hosting MathJax. Once this is merged, we can apply it to dissem.in. :)

**Comment by wetneb** [comment]
Deployed in dissem.in.
