### ISSUE TITLE
[Searx] dissemin as source of info in Science tab

### ISSUE THREAD

**Issue by jibe-b** [dissemin/dissemin#458]
Searx is a metasearch engine you may know http://github.com/asciimoo/searx

which has a "Science" tab returning scientific publications.

There already is a infoboxes returned by Wikidata. I guess Dissemin data could be used to return availability of open access versions of papers from an author, in an infobox when the query contains an author ("author:Einstein" syntax parsing is on the way).

Is it ok that I tinker on this, in particular when it comes to the traffic the server can support?

**Comment by jibe-b** [comment]
In this type of infobox, there could also be data from CORE and DOAJ I guess.

**Comment by wetneb** [comment]
@jibe-b absolutely! that would be fantastic! But I guess if you just want the availability, I would recommend to hit the oadoi API, which would give better results.

If there are some features that our UI supports but are not well exposed by our API, let me know, it is fairly easy to add a JSON endpoint somewhere. (Of course, a proper nice API for dissemin would be nice too)

**Comment by wetneb** [comment]
@jibe-b closing as this is neither a bug nor a feature request on dissemin side - if you need any specific API endpoint please open a new issue with details
