### ISSUE TITLE
[doc] improve documentation

### ISSUE THREAD

**Issue by jibe-b** [dissemin/dissemin#468]
Let's bring dissemin's documentation to another level! :)

Really good example: https://github.com/galaxyproject/training-material

**Comment by jibe-b** [comment]
More focused:

http://galaxyproject.github.io/training-material/topics/admin/

http://galaxyproject.github.io/training-material/topics/dev/

**Comment by Phyks** [comment]
I'm merging this one with https://github.com/dissemin/dissemin/issues/48.

**Comment by wetneb** [comment]
Closing this - yes we are working on it :) Feel free to open issues about more specific things that need to be documented.
