### ISSUE TITLE
SSL certificate renewal?

### ISSUE THREAD

**Issue by a3nm** [dissemin/dissemin#472]
On diego, certbot is installed as /opt/certbot/certbot-auto, but I couldn't find any cron job to renew certificates regularly. Has someone set this up, or should it be done?

**Comment by wetneb** [comment]
@a3nm I certainly haven't done anything in that regard.

**Comment by a3nm** [comment]
For reference, we just got an email from Let's Encrypt warning that the certificate would expire on 06 Dec 17 09:01 +0000, but it looks like the one we're serving will be valid for more time than this.

**Comment by a3nm** [comment]
This email is probably bogus. The certbot invocation is actually not in root's crontab but in `/etc/crontab`, and `/var/log/letsencrypt` suggests that it is indeed running. I'm also adding dissem.in, association.dissem.in, and blog.dissem.in, to my personal monitoring scripts that warn be about certificate expiry.

In any case, nothing to fix here after all. :)
