### ISSUE TITLE
Write some docs!

### ISSUE THREAD

**Issue by wetneb** [dissemin/dissemin#48]
Tons of things to do… :-(

**Comment by RaitoBezarius** [comment]
Maybe: let's do a checklist on what do we need to document, so I can help and familiarize myself to the project more?

**Comment by Phyks** [comment]
A few examples of documentation (admin / dev etc) were listed in https://github.com/dissemin/dissemin/issues/468.

Not sure what should be covered by `doc` at the moment. I'm digging again in Dissemin code and so far it seems quite good for me. There are some users who are starting hacking around Dissemin recently, we could probably extend the doc gradually based on the questions and issues they ask us.

**Comment by beckstefan** [comment]
As I am currently updating the installation instructions for the manual installation, I wonder whether we should split the manual installation into development and production in general to have a more clear guidance. Essentially, a lot of things for development and production are indeed similar, but not identical. Having both in one section is not that good for readability.

E.g. the social authentication with ORCID: Quite good for development, but how would you integrate the differences for a production environment, where you're not using sandbox and where it might be relevant, whether you use public or member API. (And you probably do not address _localhost:8080_)

Any thoughts on that?

**Comment by Phyks** [comment]
Hi,

First point I should probably mention on this is that there has been some rework of the doc recently, which is not yet deployed at https://dev.dissem.in/ (we don't have auto-deploy of the docs so far :/). So the best way to read the latest version of the doc for sure is to build it from the repo (requires `sphinx`):

```
dissemin $ make -B doc
dissemin $ cd doc/sphinx && make html
```

Typically, I introduced a section about the data model after your questions: https://github.com/dissemin/dissemin/blob/master/doc/sphinx/datamodel.rst.

> I wonder whether we should split the manual installation into development and production in general to have a more clear guidance. Essentially, a lot of things for development and production are indeed similar, but not identical. Having both in one section is not that good for readability.

Indeed, this could probably be a good idea. Not sure whether this should be full separation of development and production though (at the expense of maybe duplicating content) or rather development and production changes on top of it. @wetneb will probably have more thoughts on this.


Anyways, docs should help everyone get started (developing or setting up a production instance), so please feel free to report to us or write a pull request for any point in the doc which is not clear :) I tried to improve the doc starting again from scratch with a dev VM recently, but I have probably missed things.

**Comment by wetneb** [comment]
Docs are now hosted on readthedocs so building them is no longer a concern:
https://dissemin.rtfd.io/

They could of course be improved, but I'm closing this issue which is mostly outdated.
