### ISSUE TITLE
Use CI to check for broken links

### ISSUE THREAD

**Issue by a3nm** [dissemin/dissemin#487]
Here are some ideas of how to do it with htmlproofer: https://www.jacobtomlinson.co.uk/jekyll/2015/02/18/test-you-jekyll-blog-with-travis-ci/ and here are some people doing it https://github.com/zulip/zulip/issues/1492 https://github.com/biopython/biopython.github.io/issues/62. At least it could be done on local links (to avoid getting spammed about transient failures on remote links).

**Comment by Phyks** [comment]
Sentry should already monitor 500 errors (a server error should be an uncaught exception and Sentry catches this).

Then, there is the issue of the 404 pages. As Dissemin is mostly a dynamic website, not sure there is much to be done statically. I'd think that having server monitoring (from webserver logs) is better.

**Comment by Phyks** [comment]
Merging with #720.
