### ISSUE TITLE
[link] ORCID in Wikidata

### ISSUE THREAD

**Issue by jibe-b** [dissemin/dissemin#488]
http://magnusmanske.de/wordpress/?p=483

**Comment by a3nm** [comment]
That's an interesting link, thanks! But what do you think should be modified in Dissemin relative to this article?

**Comment by wetneb** [comment]
@jibe-b Thanks for the link! That's very exciting! As you can guess I have a few follow-up ideas ^^

**Comment by jibe-b** [comment]
Indeed @wetneb! I must say I have nothing concrete to suggest but have started to dream about a superseed of ORCID…
