### ISSUE TITLE
A paper not detected as being available from the publisher

### ISSUE THREAD

**Issue by BibliotekaITNSANU** [dissemin/dissemin#501]
The paper
Nenad Ignjatovic, Smilja MarkovicORCID, Dragana Jugovic, Dragan Uskokovic
Molecular designing of nanoparticles and functional materials
Serbian Chemical Society, Journal of the Serbian Chemical Society, 6(82), p. 607-625. http://dx.doi.org/10.2298/JSC1612070011I

is avaialble from the publisher: http://www.shd-pub.org.rs/index.php/JSCS/article/view/4288/393

**Comment by wetneb** [comment]
Hi! Thanks for reporting. We are aware that fulltext availability detection does not work very well yet. We are working on this and currently rolling out oaDOI as a new source -  this will solve this particular issue as oaDOI detects this article as being available from the publisher: https://api.oadoi.org/v2/10.2298/JSC1612070011I
