### ISSUE TITLE
Remove obsolete page that asks for name

### ISSUE THREAD

**Issue by wetneb** [dissemin/dissemin#502]
Apparently https://github.com/dissemin/dissemin/blob/master/papers/templates/papers/createProfile.html has been displayed when logging in for the first time with 0000-0002-4471-4000. We should find out why and remove this obsolete page.

**Comment by wetneb** [comment]
Apparently this is not only true for the first login, the problem remains (when the user clicks on "My profile").

**Comment by Phyks** [comment]
My two cents on this, this is likely to be explained by https://github.com/dissemin/dissemin/blob/master/papers/views.py#L339-L340.

No idea why this profile would not have a matching `Researcher` object though :/
