### ISSUE TITLE
Auto-create ORCID profiles for all ORCID authors in every paper

### ISSUE THREAD

**Issue by wetneb** [dissemin/dissemin#506]
We should basically create a Researcher for every ORCID id we know of, at Paper creation time. The newly-created Researcher would be associated to the paper but would not be fetched from ORCID (the name as it appears on the paper should be used to create the Researcher). This means that we should also update the name associated to the Researcher when we refetch it later on.

That would solve the issue of some Papers not being associated to the Researcher with a matching ORCID id.

**Comment by Phyks** [comment]
What's the status of this one after https://github.com/dissemin/dissemin/pull/694 has been merged?

**Comment by wetneb** [comment]
#694 does not create Researcher objects for all ORCID ids that appear in papers, it only makes it easier to associate these papers to the Researcher once it is created. But I guess we can close this now, it is not an approach we want to follow given that we are working on a full ORCID import. Fetching ORCID profiles on the fly at paper creation would be less efficient.
