### ISSUE TITLE
ORCID interface misses papers with bibtex citation

### ISSUE THREAD

**Issue by wetneb** [dissemin/dissemin#511]
Example profile that is incomplete: https://dissem.in/r/9372/bhojaraju-gunjal

**Comment by Phyks** [comment]
I did a quick test on my ORCID profile (https://orcid.org/0000-0002-1361-1703) and the Bibtex entry was correctly captured by Dissemin. Is there still an issue with bibtex citation?

This being said, I now removed the bibtex entry from my ORCID and am getting a ghost paper from 1970. Do you know what is happening here? https://dissem.in/r/4162/lucas-verney

I could understand the ghost part, and the need for a manual deletion from my profile. I simply don't get why this paper lost the year and went back to 1970 :/


There is the same on the example profile https://dissem.in/r/9372/bhojaraju-gunjal?page=2. 

Finally, for the example profile, there are 24 papers found versus 49 on ORCID so there is probably another issue there.

**Comment by wetneb** [comment]
Yes this would require investigating why /some/ bibtex papers are missed. If they lack authors, publication dates or titles, it's fine to ignore them, otherwise we should be able to harvest them.

The 1970 bug is also curious - that would be worth fixing too indeed.

**Comment by Phyks** [comment]
https://dissem.in/r/9656/adrien-revault-dallonnes might be impacted by this as well.

**Comment by Phyks** [comment]
@wetneb Sounds like https://github.com/dissemin/dissemin/pull/690 and https://github.com/dissemin/dissemin/pull/691 should fix this one, isn't it?

Was the unmerging maintenance ran on dissem.in?

**Comment by wetneb** [comment]
Yes indeed! The unmerging maintenance is running.

**Comment by Phyks** [comment]
\o/ <3
