### ISSUE TITLE
Search by ORCID

### ISSUE THREAD

**Issue by a3nm** [dissemin/dissemin#514]
When searching by author, it should be possible to search with an ORCID ID, and get all papers by the corresponding ORCID ID.

**Comment by Phyks** [comment]
So, I think I could handle this:

1. On the front page, in the search field "any author", if the query matches an ORCID ID, we could simply redirect to the `/<ORCID_ID>` page.
2. On the search page, there would be an extra "by ORCID" field to search by ORCID (multiple values possible, split on space). We could probably use some frontend item such as https://bootstrap-tagsinput.github.io/bootstrap-tagsinput/examples/.

I just have to look up how search is working backend-side to add a filter on ORCID values.

What do you think about this plan?

**Comment by wetneb** [comment]
Item 1 sounds like a no-brainer indeed!
For item 2, we should be careful of not overloading this search form too much - I think it is already quite confusing. Some of these fields could be moved to an "advanced search" page.

What is the motivation for searching for multiple ORCID ids? Do you have a particular use case in mind?

**Comment by wetneb** [comment]
Also, if we let people input orcid ids in the search form on the main page, then I think by consistency they should also be allowed in the authors field of the form on https://dissem.in/search/ - so I would lean towards just reusing this field and not introducing a new one.

**Comment by Phyks** [comment]
> What is the motivation for searching for multiple ORCID ids? Do you have a particular use case in mind?

I was just having the symmetry in mind "by authorS" (multiple authors possible), so by ORCIDs.

> Also, if we let people input orcid ids in the search form on the main page, then I think by consistency they should also be allowed in the authors field of the form on https://dissem.in/search/ - so I would lean towards just reusing this field and not introducing a new one.

So whatever word (split on whitespace) matches an ORCID ID regex, should be considered as an ORCID ID and added to the search filter as such. The rest of the words will be passed down to the authors such as currently done.

**Comment by wetneb** [comment]
Note: currently, this will only work for ORCID profiles that we have already fetched. We have plans to fetch all of them anyway.
