### ISSUE TITLE
"FirstName LastName" should be the same as "LastName FirstName" 

### ISSUE THREAD

**Issue by Bisaloo** [dissemin/dissemin#516]
I had a colleague complaining they could only find one their own papers on Dissemin today.

Turns out they were searching with "LastName FirstName" instead of "FirstName LastName". I feel like Dissemin could probably be a bit more clever here.

I can provide the name of this person by email if needed. I'd rather not post it on a public bug tracker without their explicit agreement though.

**Comment by Phyks** [comment]
Closed by #642.
