### ISSUE TITLE
False positive from library.tue.nl

### ISSUE THREAD

**Issue by nemobis** [dissemin/dissemin#519]
https://dissem.in/10.1021/ma0502811 says there's a PDF at http://library.tue.nl/csp/dare/LinkToRepository.csp?recordnumber=620952 , which however just redirects to https://tue.on.worldcat.org/discovery . Can the Technische Universiteit Eindhoven possibly have broken all incoming links just like that?

On <https://tue.on.worldcat.org/search?databaseList=&queryString=Shear+Degradation+Resistance+of+Star+Polymers+during+Elongational+Flow> there are two results with a "full text" button, but I have no idea where they go: the link target is http://linker2.worldcat.org/ and requires login.

http://opendoar.org/id/567/ has http://repository.tue.nl/ which redirects to https://research.tue.nl/ which eventually finds https://research.tue.nl/en/publications/shear-degradation-resistance-of-star-polymers-during-elongational (some Elsevier tracking thing) where I meet a lot of tracking JavaScript but no full text.

**Comment by wetneb** [comment]
Migrating all fulltext availability errors to #602 for clarity.

**Comment by nemobis** [comment]
All links to http://library.tue.nl/ keep being broken after over one year. This domain seems unsalvageable, all links should be removed.
