### ISSUE TITLE
question: how to use dissemin as a python client for https://dissem.in/api/?

### ISSUE THREAD

**Issue by monperrus** [dissemin/dissemin#523]
I want to use the Dissemin API (https://dissem.in/api/) in python code.

Instead of creating my own HTTP request and parsing the JSON response, I guess that dissemin itself can be used as python client for its own web API.

How to do this?

**Comment by wetneb** [comment]
I just use the `requests` library for that. You can see an example of use here:
https://github.com/dissemin/oabot/blob/master/src/oabot/main.py#L199
