### ISSUE TITLE
False positive for DOAJ

### ISSUE THREAD

**Issue by nemobis** [dissemin/dissemin#525]
https://dissem.in/10.1016/S0313-5926(10)50004-3 clams full text is available from https://doaj.org/article/c567f417f7444487a81dbafe43fbcd4f , which however is a 404. OAdoi here redirects to the publisher.

The ResearchGate PDF also disappeared, and it's an Elsevier paper, so I guess it might be related to the recent brouhaha. Does DOAJ really host any PDF?

I've also seen cases where the DOAJ page only provides an abstract.

**Comment by wetneb** [comment]
Migrating all fulltext availability errors to #602 for clarity.
