### ISSUE TITLE
False positive for publications.jrc.ec.europa.eu

### ISSUE THREAD

**Issue by nemobis** [dissemin/dissemin#527]
There are a few dozens suggestions in OAbot for works like https://dissem.in/10.1126/science.1184984 which claims http://publications.jrc.ec.europa.eu/repository/handle/JRC59049 has a PDF, while there's no file attached. OAdoi redirects to the publisher URL.

**Comment by wetneb** [comment]
Migrating all fulltext availability errors to #602 for clarity.
