### ISSUE TITLE
Increase upload size limit

### ISSUE THREAD

**Issue by nemobis** [dissemin/dissemin#528]
Currently Dissemin only allows to upload PDF files up to 20 MB. Is there any hard limit or is this threshold arbitrary?

It's not uncommon for an article to be 30 or 40 MiB, for instance https://archive.org/download/ieee-us-government-works/ieee-us-government-works.zip/10.1109%2Figarss.2016.7730450.pdf

I think 50 MiB would be a reasonable limit.

**Comment by wetneb** [comment]
It's entirely arbitrary and can be changed here: 
https://github.com/dissemin/dissemin/blob/7097358a4729e08d8155b59019040e949c0a6fd5/dissemin/settings/common.py#L118
