### ISSUE TITLE
question support for redirection to OA based on doi?

### ISSUE THREAD

**Issue by monperrus** [dissemin/dissemin#535]
Hi dissemin team,

Do you have an endpoint that provides HTTP redirection to the open-access version such as oadoi and doai?

Example: https://oadoi.org/10.1109/ICSE.2012.6227139
```
< HTTP/1.1 302 FOUND
< Content-Type: text/html; charset=utf-8
< Location: http://arxiv.org/pdf/1203.5188
< 
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>Redirecting...</title>
<h1>Redirecting...</h1>
* Connection #0 to host oadoi.org left intact
<p>You should be redirected automatically to target URL: <a href="http://arxiv.org/pdf/1203.5188">http://arxiv.org/pdf/1203.5188</a>.  If not click the link.
```

**Comment by wetneb** [comment]
Hi @monperrus,
Yes we have this, it is called doai.io and it was what inspired oadoi.org :) It is not maintained though, we recommend using oadoi.org.

**Comment by monperrus** [comment]
> doai.io [...] is not maintained though, we recommend using oadoi.org. 
very good to know, thanks a lot.
