### ISSUE TITLE
question: how often is HAL crawled?

### ISSUE THREAD

**Issue by monperrus** [dissemin/dissemin#536]
Regularly, some entries are updated on HAL.

How long does it take before the change propagates to dissemin? how often is HAL crawled?

**Comment by nemobis** [comment]
I don't know the exact answer, but one data point: BASE states it crawls its sources every 2 weeks.

**Comment by Phyks** [comment]
There has been some issues with papers ingestion recently, so it is possible the database is missing some recent papers, we are currently working on fixing this (and there are a few issues here to track this). 

I think that in the regular situation harvesting from databases should be weekly.

**Comment by monperrus** [comment]
ok, thanks.
