### ISSUE TITLE
Works clustered with their reviews

### ISSUE THREAD

**Issue by nemobis** [dissemin/dissemin#542]
https://dissem.in/p/66403509/tuberculosis-of-the-frontal-sinus clusters https://doi.org/10.1097/00000441-191701000-00057 and https://doi.org/10.1097/00000441-191601000-00067, presumably for having the same title and author, but they were in different years http://api.crossref.org/works/10.1097/00000441-191701000-00057 10.1097/00000441-191601000-00067 and judging from https://zenodo.org/record/1555094 one is the review of the other.

Similarly, I've seen works clustered with their review hosted on PubMed, whose author is marked as "NA", so maybe the author match should be stricter.

**Comment by nemobis** [comment]
I'll comment on the more general case in https://github.com/dissemin/dissemin/issues/512

**Comment by wetneb** [comment]
Closing this as duplicate, we'll use #512 instead.
