### ISSUE TITLE
Outdated locales on dissem.in?

### ISSUE THREAD

**Issue by Phyks** [dissemin/dissemin#554]
It seems locales are outdated on dissem.in.

See https://dissem.in/r/62964/dietmar-thal, in German. It's coming from https://github.com/dissemin/dissemin/commit/7eb84fec2cd59f0c8c7f4d1c7ab1e22bc182fc72#diff-e09358eca52f770a64b95dfd20725f1cR1233 I think, which is not yet deployed in production.

**Comment by wetneb** [comment]
yes, deployment is manual at the moment. This might be something we want to improve.

**Comment by Phyks** [comment]
Thanks for redeploying! Not sure there is much value in having a more automated deployment at the moment, this looks like a time consuming tasks for little immediate benefit :/

Closing this as the original issue is solved. Feel free to reopen if I missed something.
