### ISSUE TITLE
Update pyoai to newest version

### ISSUE THREAD

**Issue by wetneb** [dissemin/dissemin#569]
We currently use a custom fork of pyoai. In the meantime the project has had a revival and is now compatible with Python 3. We should migrate to their latest versions and submit any missing patches to them.

**Comment by wetneb** [comment]
The custom fork is at https://github.com/wetneb/pyoai

**Comment by Phyks** [comment]
Seems like we only need https://github.com/wetneb/pyoai/commit/807d63abb96bc4bf4bf923413d459479db056cef to be able to use the upstream up to date `pyoai` version. Could you post a message to bump https://github.com/infrae/pyoai/pull/8 maybe?
