### ISSUE TITLE
Migrate to Python 3

### ISSUE THREAD

**Issue by wetneb** [dissemin/dissemin#572]
Once #569, #570 and #571 are solved we should be able to migrate to Python 3.

**Comment by Phyks** [comment]
Note to self:

* `ack "^\s*print " --ignore-dir .vm_venv` should be replaced with print functions.
* `ack "unicode\(" --ignore-dir .vm_venv` should be replaced with calls to `str`.

**Comment by wetneb** [comment]
Isn't that done by `2to3`?

**Comment by Phyks** [comment]
Sure, but doing it by hand will probably make a shorter `2to3` diff.
