### ISSUE TITLE
Write unittest for 404 when invalid DOI or pk given

### ISSUE THREAD

**Issue by Phyks** [dissemin/dissemin#576]
> Given that this error was triggered when accessing https://dissem.in/10.1blabla it should not be too hard to write a unit test for this.

See https://github.com/dissemin/dissemin/pull/556#issuecomment-460056447.

**Comment by wetneb** [comment]
My comment referred to the invalid DOI case - it's not clear to me how the view can be triggered without any DOI or pk?

**Comment by Phyks** [comment]
Indeed, I went too fast when opening this. Anyways, this was basically just a reminder for me to handle it ASAP and avoid having your comment getting lost in my emails.

**Comment by Phyks** [comment]
Oh, you already handled it actually https://github.com/dissemin/dissemin/commit/0d01e1d60422930e9c987b91e91f050125e9aa4a. Thanks!

Closing.
