### ISSUE TITLE
Usage statistics on the main page

### ISSUE THREAD

**Issue by wetneb** [dissemin/dissemin#577]
We want more statistics about usage, both public (to advertise the service) and private (for us to monitor and fix things).

From @a3nm in a coordination email thread:
>   Gathering more statistics about Dissemin usage, just because it makes
>   things more motivating for us to see people using Dissemin, talking
>   about Dissemin, etc. There are already some clues suggesting that
>   people know about the service, but I think we're not seeing the whole
>   picture and seeing it might motivate us more. Concrete ideas:
> 
>   - running some analytics (at least on the web server logs) to estimate
>     the number of page views, number of articles downloaded via
>     Dissemin, etc. (in addition to uploads),
>   - setting up Google Webmaster Tools to see incoming links to dissemin,
>   - scripting the computation of aggregate stats on deposits,
>   - displaying the stats on the main page of dissem.in

And @Phyks 

> +1 for this, it could be nice to have more statistics about usage. This could provide an easy dashboard to detect issues (agreggating sentry.io returns for instance) and have some nice and motivating metrics. They have https://adresse.data.gouv.fr/data/stats/stats-api-2018.html at http://adresse.data.gouv.fr/ for instance

**Comment by nemobis** [comment]
How long does it take to complete the query for the number of users who deposited something?

**Comment by beckstefan** [comment]
We could add a carousel on the start page and fill three to five pages with information and statistics. 

As a start
* slide on green open access, including the pie chart
* slide on open repositories
* slide on how many publications have been deposited
* slide with success story, e.g. finding a publication uploaded with Dissemin which has a lot of downloads or something like that

**Comment by Phyks** [comment]
> How long does it take to complete the query for the number of users who deposited something?

Running time is not so much an issue I think since this can always be (and should probably be) cached and recomputed in the background periodically.


> We could add a carousel on the start page and fill three to five pages with information and statistics.

What would be the open repositories slide? This could maybe also just be a wall of blocks (without sliding through), we already have two blocks on the main page.



Additionally, I guess this issue is two-fold:

1. Having impacting numbers on the front page to show the magnitude of the project. I kind of like the Unpaywall "realtime updating" number of articles for this http://unpaywall.org/ (although the number is probably updating a bit too slow to be well noticeable).
2. Having statistics for our own usage.

The second point is of particular importance for refactoring JS frontend for instance (if nobody is using legacy browsers, that's a huge bonus for us). I would suggest having a https://goaccess.io/ running on the production logs.

**Comment by beckstefan** [comment]
> What would be the open repositories slide? This could maybe also just be a wall of blocks (without sliding through), we already have two blocks on the main page.

We do have a box on open repositories. 

I am not a huge fan of slides/carousel, but I like them for not-that-important-information. Boxes are nice  if they fit into a grid. This requires almost equal sizes and this requires few content. Extending the current systems seems hard to me. In German locales, the left box has almost double the height as the right box.

Another idea might be something were the user scrolls down and experiences all the nice things we have one after another.

**Comment by Phyks** [comment]
> This requires almost equal sizes and this requires few content.

I had something like this in mind https://masonry.desandro.com/layout.html, but I don't really know how this would render with text, indeed.

> Another idea might be something were the user scrolls down and experiences all the nice things we have one after another.

This is really trendy I think, but I'm not sure it would be a good fit for Dissemin. http://www.html-tidy.org/ / https://kresus.org/ / … there are tons of websites with this idea of "screens" that you can scroll through.

Personally, I like a lot the topmost block on home page, showing a simple caption about what Dissemin does and letting user fill in the search field immediately to start exploring (although related to #696), with more details down the page to explain better what this is about.

I think we should probably try to list what we want / need on this front page and see how to fit this in. Slides / carrousel might end up as being one of the best solution :)
