### ISSUE TITLE
Document the deployment process

### ISSUE THREAD

**Issue by wetneb** [dissemin/dissemin#578]
We should have docs about how we deploy dissemin to https://dissem.in/ and the docs to https://dev.dissem.in/.

**Comment by wetneb** [comment]
Docs are now deployed automatically on https://dissemin.rtfd.io/

**Comment by Phyks** [comment]
Note: https://dev.dissem.in/ does not redirect (yet?) to https://dissemin.rtfd.io/.

**Comment by wetneb** [comment]
@Phyks for me it does… could it be a cache issue on your side?

**Comment by Phyks** [comment]
Indeed! :)

**Comment by Phyks** [comment]
Is there anything special to document to close this one?

**Comment by wetneb** [comment]
Yeah I think that's much better now, especially with the Celery setup.
