### ISSUE TITLE
Investigate downtime as reported by downnotifier

### ISSUE THREAD

**Issue by wetneb** [dissemin/dissemin#579]
We use a downnotifier.com alert on http://dissem.in/r/7877/kurt-mehlhorn which must contain "Improved balanced flow computation using parametric flow" to be considered up. This fails quite often and we must understand why. Perhaps dissemin takes too long to respond.

**Comment by wetneb** [comment]
@Phyks there was some downtime today when I restarted the server - that one is not spurious.

**Comment by Phyks** [comment]
Looks like we no longer have downtimes since we partially resolved the out of disk space errors :)

**Comment by wetneb** [comment]
Yes the website is a lot faster too! Closing then.
