### ISSUE TITLE
Add monitoring for Celery

### ISSUE THREAD

**Issue by wetneb** [dissemin/dissemin#597]
We should have a way to be notified when Celery unexpectedly stops in production as it stalls all asynchronous tasks. This would happen (for instance) when we run out of disk space.

More generally we might want to improve the way we deploy and update celery (kubernetes?).

**Comment by wetneb** [comment]
For now, here is how deployment is done:
- dissemin itself runs as a WSGI script loaded by Apache
- celery is launched in a screen with `./celery.sh` (as `dissemin` user)
- elasticsearch is launched in a screen with `elasticsearch -d` (as `dissemin` user)

**Comment by Phyks** [comment]
Ok. I guess writing systemd units for celery and elasticsearch could help here. There would be auto-restart for free basically, and eventually some notifications.

**Comment by Phyks** [comment]
Concerning elasticsearch, I think we should probably install it through the `deb` packages, https://www.elastic.co/guide/en/elasticsearch/reference/current/deb.html.

This would probably ease maintenance and upgrade. Additionnally, it comes with a SysV/Systemd unit https://www.elastic.co/guide/en/elasticsearch/reference/current/deb.html#deb-running-systemd. This will provide autostart.

Autorestart is not provided by the unit, but this can be easily added on top.


Writing a unit for celery should not be very difficult either.

**Comment by beckstefan** [comment]
celery is slightly tricky, since their docs do not say anything about celery _beat_, which can indeed be run as daemon, but it lacks a proper stop command.

For celery _beat_ systemd unit:
https://github.com/celery/celery/issues/4304

**Comment by wetneb** [comment]
Done as part of the migration to the new servers.
