### ISSUE TITLE
Migrate sphinx docs to Markdown

### ISSUE THREAD

**Issue by wetneb** [dissemin/dissemin#604]
Because RST syntax is confusing and ReadTheDocs supports markdown:

https://docs.readthedocs.io/en/latest/intro/getting-started-with-sphinx.html#using-markdown-with-sphinx

`pandoc` can be used for the conversion of existing documentation.

**Comment by Phyks** [comment]
Actually, not sure it is as simple as running `pandoc`. It does not seem to convert nicely all the Sphinx-related RST commands :/

**Comment by wetneb** [comment]
@Phyks I think we can only do it for the doc pages we write ourselves (such as `install.rst`), not the autogenerated ones from the code.

**Comment by wetneb** [comment]
Hmmm maybe http://www.ericholscher.com/blog/2016/mar/15/dont-use-markdown-for-technical-docs/ kind of half-convinced me we should stick with RST… but their syntax is just so abstruse, it's terrible

**Comment by wetneb** [comment]
Okay let's not do it then! (This way we close an issue, yay!)
