### ISSUE TITLE
error in the Brazilian Portuguese language

### ISSUE THREAD

**Issue by eduaddad** [dissemin/dissemin#615]
The Brazilian Portuguese language is the same as the Portuguese of Portugal and in translatewiki it differs in both languages

**Comment by wetneb** [comment]
That seems to be due to a discrepancy between the language codes in Django and in Translatewiki.
Django expects Brazilian Portuguese translations to have code `pt_BR` whereas Translatewiki adds them as `pt-br`.

https://docs.djangoproject.com/en/2.1/topics/i18n/#definitions

**Comment by eduaddad** [comment]
will it be fixed at some point?

**Comment by wetneb** [comment]
@eduaddad I hope so!

**Comment by Nikerabbit** [comment]
It's easy to change. We have a "code map" feature exactly for that. You just need to provide a list of codes to map (or even submit a patch via https://gerrit.wikimedia.org to the translatewiki repo if you feel adventurous).

Here is an [example](https://gerrit.wikimedia.org/r/plugins/gitiles/translatewiki/+/refs/heads/master/groups/FreeCol/FreeCol.yaml#14) and [documentation](https://www.mediawiki.org/wiki/Help:Extension:Translate/Group_configuration).

**Comment by Nikerabbit** [comment]
I pushed an update with the [new code map](https://gerrit.wikimedia.org/r/c/491924/). Does it look ok now?

**Comment by wetneb** [comment]
@eduaddad this is now fixed and deployed.
