### ISSUE TITLE
Names links on profile does not work

### ISSUE THREAD

**Issue by Phyks** [dissemin/dissemin#629]
On an author profile page, there is a list of alternative names (disambiguation). I think this is only shown when logged in as an admin.

Typically, for my profile, this looks like

![capture d ecran 2019-02-28 a 11 33 52](https://user-images.githubusercontent.com/3856586/53560526-da727c00-3b4c-11e9-8da8-9dbc95aec53d.png)

Clicking the link redirect to `https://dissem.in/search/?authors=<AUTHOR_ID>` and it does not work. Not sure what should be done here, but I guess this should either be a search on `AUTHOR_ID` or a fulltext search on disambiguated author name.

**Comment by wetneb** [comment]
Yes we should remove these names - I will actually remove the corresponding model altogether, I think, as this is a leftover from the previous author name disambiguation heuristics.

**Comment by Phyks** [comment]
Same for metadata links (in https://dissem.in/p/9364/hybridization-of-first-and-second-sound-in-a-weakly-interacting-bose-gas for instance) after decommissioning doai.

**Comment by wetneb** [comment]
Fixed by #664.
