### ISSUE TITLE
Paper page should display publication date

### ISSUE THREAD

**Issue by wetneb** [dissemin/dissemin#633]
The paper page currently does not display the publication date (or year):
https://dissem.in/p/99648067/carvacrol-rich-oregano-oil-and-thymol-rich-thyme-red-oil-inhibit-biofilm-formation-and-the-virulence-of-uropathogenic-escherichia-coli

We should add it somewhere!

**Comment by beckstefan** [comment]
It is indeed somewhere:

![year_is_there](https://user-images.githubusercontent.com/29397922/54822910-6720dd80-4ca6-11e9-8515-af2a4e3e9c87.png)

Maybe we could it put somewhere into the right box.

![published_in](https://user-images.githubusercontent.com/29397922/54826422-16ae7d80-4cb0-11e9-8f4c-d6980c3073ea.png)

Or add _from_ after list of authors.

**Comment by wetneb** [comment]
Ah, makes sense! Yes I was thinking adding it to either the right box or the main panel. Near the authors would indeed be quite natural I think.

**Comment by Phyks** [comment]
I was thinking about having the date of publication as a "Published on" item close to the "Published in" section on the right panel. The formulation and so on might vary but definitely :+1: for having it in the right panel.

I am working on Bibtex export of metadata at the moment, and I think the right panel should provide an overview of the rest of the available metadata (beside title / authors / abstract) such that it makes clear what would be exported with the "Export citation" link which will lie close to the "request via OAB" link.

**Comment by beckstefan** [comment]
Having the pubdate with the authors seems natural to me, too.

If it's in the box, the best way is probably to put the date into the citation proposals. I just tried with a small browser window: The box is going first, i think it should be go down, as it provides no the primary information: OA status.
