### ISSUE TITLE
Title of TOS page is "Frequently Asked Questions"

### ISSUE THREAD

**Issue by wetneb** [dissemin/dissemin#652]
It should rather be "Terms of Service".
https://dissem.in/tos

**Comment by Phyks** [comment]
Not sure about the current Apache setup, it might be worth mentionning storage of IPs in the logs.

**Comment by beckstefan** [comment]
Yes, the common opinion is that GDPR requires mentioning of logs (what is saved and how long) and probably some more details on cookies set.
