### ISSUE TITLE
Interface to deposit is in German?!

### ISSUE THREAD

**Issue by a3nm** [dissemin/dissemin#658]
I'm on the page https://dissem.in/deposit_paper/102422767/?type=postprint logged in with my ORCID account https://orcid.org/0000-0002-7977-4441 and when selecting the HAL repository, the label of some fields are in German?! See the bottom of this screenshot:

![2019-03-25T17:45:28,182888598+01:00](https://user-images.githubusercontent.com/843551/54938001-6fcf1900-4f1d-11e9-9555-c4e375dddc07.png)

Any idea why? Is this a problem with localization maybe?

**Comment by wetneb** [comment]
I can confirm the bug, it's very curious indeed! The translations look fine, it might be a problem with django-crispy-forms.

**Comment by wetneb** [comment]
Fixed by compiling the translations again, with `./manage.py compilemessages`.

**Comment by a3nm** [comment]
Also fixed for me, thanks!

That said... maybe I'm being paranoid, but any idea of why this happens and whether it could happen again? I think if the interface looks like this to a user then they won't figure out what to do and they won't deposit, and we may not notice it until after a while :-P so maybe it could be worth it having some reassurance that it won't recur?

**Comment by wetneb** [comment]
Unless we review all translations coming from Translatewiki, I don't really know how we can avoid it… I am not sure if Translatewiki supports submitting translations as pull requests rather than pushing to master, if so, that could be a solution. Otherwise, Weblate does that well.
