### ISSUE TITLE
Main page search form

### ISSUE THREAD

**Issue by Phyks** [dissemin/dissemin#661]
Hi,

I was thinking about the search form on the index page. I recently discovered inadvertently that the search form supported more complex syntax than just "First Last". I don't see documentation on this (and discoverability would be better anyways) and I don't think a user could discover it on its own.

The currently supported syntax is (FIRST and LAST are placeholders):

* "FIRST LAST" (or "LAST FIRST", see #516 and #642).
* "last:LAST" to enforce last name.
* "ORCID_ID" to enforce an ORCID Id.
* Comma for enforcing separation of the names.

First question is why don't we support the "first:FIRST" counterpart of "last:LAST"? If my name is "Martin" for instance, I guess the impact of enforcing it to be last name, but this is likely to not be enough to further filter.

We might be able to handle it in a similar way as Github, with a link below the search input "See help for advanced search syntax" linking to a FAQ entry similar to https://help.github.com/en/articles/searching-issues-and-pull-requests.

What do you think?

**Comment by beckstefan** [comment]
Sounds very good.

I don't know if makes sense for this search, but people are used to quotes from Google Search, i.e. to enforce to search for "Martin Daniels" as phrase they will type `"Martin Daniels"`.

As a bonus we could add on the start page with the search field an advanced search button to make user input easier than reading documentation.

**Comment by Phyks** [comment]
Thinking about it, supporting both commas and quotes is going to be a nightmare (and probably also for users). So we should probably drop commas as separators if we want to support quotes. I don't have very strong opinions here, I'd tend to think commas are easier to handle and already here (so we have backward compatibility supporting them).

For the rest of the issues discussed here, I have an incoming PR.

**Comment by Phyks** [comment]
Actually, supporting both first: and last: would probably require quotes (and much more search logic).

For instance, if I want to search for `first:"Paul André" last:Dupont`. I'd rather be in favor of keeping the statusquo so far and maybe have a separate issue tracking improved search logic if there is a need for it (is there?).

**Comment by a3nm** [comment]
Naive opinion here: advanced search operators in the search field of the main page are not easily discoverable (I didn't know about them either) and I don't expect that many people will use them.

My opinion would be that it's fine not to bother with them too much (e.g., make the simplest possible choices in terms of parsing), and encourage users that want to make complicated queries to use the advanced search page. (In particular when the user submits a query with advanced operators that cannot be parsed properly.)
