### ISSUE TITLE
Search form on Researcher view does not make sense

### ISSUE THREAD

**Issue by wetneb** [dissemin/dissemin#663]
I think it is confusing to have a full search form on the right-hand sido of a researcher page such as https://dissem.in/r/142737/louise-ejsing.

For instance, it is counter-intuitive to have a field for author names: we are already looking at a view that filters by authors, but that field is empty. In reality, this could be useful if you want to look for a particular co-author of the profile you are looking at, only returning the papers authored by both, but that's kind of advanced and probably too confusing to be there in plain sight, no?

**Comment by Phyks** [comment]
What about simply renaming "By authors" to "By coauthors"?

**Comment by wetneb** [comment]
Yes, why not actually!
