### ISSUE TITLE
uploadUrl is not defined

### ISSUE THREAD

**Issue by wetneb** [dissemin/dissemin#665]
When trying to upload https://arxiv.org/pdf/1411.3827 at https://dissem.in/deposit_paper/8652/, I get the error "Invalid URL.".

**Comment by Phyks** [comment]
For the record, this is coming from a JS error "`uploadUrl` is not defined" I think. See https://sentry.io/organizations/dissemin/issues/943554491/?query=is%3Aunresolved.

**Comment by wetneb** [comment]
No this was solved by the permission fix… I can upload fine now, but I still have the uploadUrl error in the console. Let's repurpose the issue then!
