### ISSUE TITLE
Bibtex export: filename of the downloaded file

### ISSUE THREAD

**Issue by wetneb** [dissemin/dissemin#666]
Because we are using the API by DOI, somehow my firefox tries to make up a filename based on  a part of the DOI:

![image](https://user-images.githubusercontent.com/309908/55035153-0f200900-500f-11e9-9c77-17b6e48fa7a0.png)

I guess we could either:
* declare a new view, with a different URL, that would generate a clean filename
* set the HTTP headers so that the file is viewed directly in the browser instead (I think that's what Google Scholar does and it's more user-friendly: people expect to be able to copy-paste, saving files is more complicated.)

**Comment by wetneb** [comment]
Using an endpoint that is independent of the DOI would also help to generate citations for papers without DOIs. I think we could enable the bibtex export for all papers, otherwise it is a bit confusing for users who expect to find the feature on another paper and get disappointed.

**Comment by Phyks** [comment]
`download="filename"` on the link should do the trick to specify the filename (https://www.w3schools.com/tags/att_a_download.asp). Filename could be something like `{slug}.bib` maybe?

:+1: for having an endpoint for any document, including without DOI. This should not be very difficult to do, I'll have a look into it.

**Comment by wetneb** [comment]
@a3nm what's your view on downloading a file or displaying the plain text in the browser?

**Comment by Phyks** [comment]
Note that currently, it is only downloading because the MIME-Type is `application/x-bibtex` which Firefox does not know how to handle :/ There is no force-download at the moment, and Firefox could definitely choose to show the plaintext response.

I'd rather not return a MIME type for plain text, because this is not really plain text.

**Comment by wetneb** [comment]
Yeah it is sad to have to put an inaccurate content type, but for me usability should come first I think. Maybe it makes sens to keep the correct content-type for the API (potentially adding support for content negociation there) and use plain text for another URL with a download-friendly filename (the `download="filename"` could work, but not if people embed the link from somewhere else or use `wget` for instance).

**Comment by a3nm** [comment]
My opinion would be that it's better to show the bibtex in the browser, maybe in a div where it's easy to copy-and-paste. There could also be a download link, in which case I'd expect the filename to be something like the bibtex citation key "doe2042foobar" (where doe is the last name of the first author, 2042 is the publication year, foobar is the first non-stopword word of the article title), with the ".bib" extension. But probably the slug is OK too.

**Comment by Phyks** [comment]
Displaying it in a div is probably a good idea indeed. After reviewing a bit what others do, some force download the file (which is actually quite annoying) while others show the bibtex and it's probably best.

My option would be to have "Export citation" link open a modal (https://getbootstrap.com/docs/4.0/components/modal/) with a select list to pick the format of the citation wanted (Bibtex only so far, probably plain text and end note could come easily). A div would display the citation in the modal, and there would be a download button.

The whole interface could work like https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.105.257003, which is actually quite user friendly in my opinion.

**Comment by a3nm** [comment]
Yup that's perfect except that their modal is not high enough, so you
need to scroll for no good reason.
