### ISSUE TITLE
Export list of papers

### ISSUE THREAD

**Issue by Phyks** [dissemin/dissemin#688]
Now that we have Bibtex export of citations for individual papers, we could add export for list of papers.

On researcher page, it would be fairly easy to add export of all the papers from the researcher as BibTeX.

On search page, I've mixed feelings about this. I'd like to add the ability to export search results to BibTeX. The issue is that with a wide search, exporting 1M papers to BibTeX is simply not realistic. Not sure about the best approach here:
* Only offer BibTeX export for searches with few enough results (but this is a bit arbitrary and might be difficult to understand for the users).
* Only offer BibTeX export of the current page (maybe the best solution).

What do you think about the search page? Would it be worth it?

**Comment by wetneb** [comment]
Random idea: we could restrict the export to researcher profiles - that rarely grows beyond 1000 papers I would say. But it might not be flexible enough for all use cases?

Bibtex export for the current page would be fairly simple to understand and has the benefit of being constant with the JSON export - both of them would have the same paging, so we would get rid of all performance issues.

**Comment by Phyks** [comment]
> Random idea: we could restrict the export to researcher profiles - that rarely grows beyond 1000 papers I would say. But it might not be flexible enough for all use cases?

Yes, I definitely think it could be worth having BibTeX export for researcher profiles! :) Will do.

> Bibtex export for the current page would be fairly simple to understand and has the benefit of being constant with the JSON export - both of them would have the same paging, so we would get rid of all performance issues.

I agree with this, I'll see how this can be integrated in the search results.
