### ISSUE TITLE
Search tooltip misaligned

### ISSUE THREAD

**Issue by beckstefan** [dissemin/dissemin#702]
The tooltip content is misaligned. The bullets are left aligned while their text is centered. This looks a bit weird and confusing to me.

![search_tooltip](https://user-images.githubusercontent.com/29397922/55542970-63d71a00-56c8-11e9-994e-574ad4bf2b23.png)

(Maybe brighter bullets would be nice.)

**Comment by Phyks** [comment]
Indeed, will fix!
