### ISSUE TITLE
False positive for IUCR.org

### ISSUE THREAD

**Issue by nemobis** [dissemin/dissemin#703]
https://dissem.in/p/60679495/ says the full text is available at http://journals.iucr.org/a/issues/1985/03/00/a24269/a24269.pdf , which however is password protected and upon failure redirects back to the toll-access Wiley page.

The Unpaywall data as of 2019-03-28 doesn't contain the IUCR URL.

**Comment by wetneb** [comment]
@nemobis can you add that to #602 instead? I don't think we want to open an issue for every single instance of this problem.

**Comment by nemobis** [comment]
Antonin Delpeuch, 08/04/19 12:11:
> @nemobis <https://github.com/nemobis> can you add that to #602 
> <https://github.com/dissemin/dissemin/issues/602> instead? I don't think 
> we want to open an issue for every single instance of this problem.

I can, I just saw that issue too late. I'm also not sure what criteria 
you followed to determine that the issues were related, or did you?

**Comment by wetneb** [comment]
Generally, all false positives or false negatives for full text detection should go there, unless there is a particular distinct cause that can be attributed to them.

**Comment by nemobis** [comment]
Antonin Delpeuch, 08/04/19 14:22:
> Generally, all false positives or false negatives for full text 
> detection should go there, unless there is a particular distinct cause 
> that can be attributed to them.

Is "URL is password protected" a distinct cause?

**Comment by nemobis** [comment]
Or in other words, given I don't know what warrants a separate issue, is 
it fine if I create separate issues and then self-close them to add to 
the list in your issue? Having a separate issue is much easier for me to 
track whether something was reported or not and what's the status.

**Comment by wetneb** [comment]
Sure!
