### ISSUE TITLE
Incentives for depositing more than the PDF file

### ISSUE THREAD

**Issue by Phyks** [dissemin/dissemin#704]
Hi,

[arXiv](http://arxiv.org/) has a strong incentive to deposit source files directly, so that they have both the TeX (or other source file) document as well as the PDF. This way, sources are available (BibTeX bibliography, separate figures files, TeX source), which can be super useful, in particular for more extractions and processing of the articles.

I'm not very well versed into Zenodo and other deposit interfaces in Dissemin, but I was thinking that maybe Dissemin could reproduce the same incentives to have both the PDF files as well as the source files (and let us even dream, the data behind the papers).

A possible way of doing it would be to have a first upload box asking for source files, and have a "Only upload PDF file" link to revert to the single PDF file upload.

Besides the technical questions, this is not an easy question in terms of usability though. The point, in the end, is to have as much deposits as possible (and as complete as possible), and requiring too many steps or too much files might discourage some authors.

**Comment by wetneb** [comment]
See also #225

**Comment by Phyks** [comment]
Oops, I missed this one. Let's merge them.
