### ISSUE TITLE
Refetch ORCID publications is broken

### ISSUE THREAD

**Issue by Phyks** [dissemin/dissemin#716]
Steps to reproduce:

1. Go to https://dissem.in/my-profile
2. Click "Refresh papers"
3. All papers are displayed, not only the ones from the researcher.

When clicking "refresh papers", the XHR call is bogus, it is https://dissem.in/ajax/search. This is probably linked to a recent change actually (such as fixing the JSON bug when going backwards).

**Comment by a3nm** [comment]
I can reproduce this. Also, when selecting a high page number (such as 10), it leads to a 404.

**Comment by Phyks** [comment]
Same issue happens on a researcher page as well, when searching for instance.
