### ISSUE TITLE
Searching for a paper by title doesn't work

### ISSUE THREAD

**Issue by a3nm** [dissemin/dissemin#724]
Searching for "treewidth computations" gives no results : https://dissem.in/search/?authors=treewidth+computations

However there's at least one matching paper (from 2010) https://dissem.in/p/30724126/treewidth-computations-i-upper-bounds

This sounds weird, is it a problem with indexing?

**Comment by a3nm** [comment]
Same problem with https://dissem.in/search/?authors=When+is+the+Evaluation+of+Conjunctive despite https://dissem.in/p/160997/when-is-the-evaluation-of-conjunctive-queries-tractable

**Comment by Phyks** [comment]
Looking at the URL, you are searching for an **author** matching "treewidth computation", which yields no results.

Not sure how you got there, seems that both advanced search and sidebar search are working. If you typed this in the index page search box, this should be covered by #661 :)

**Comment by a3nm** [comment]
Oh, sorry, I just used the main search field on dissem.in. Yeah, I expected this field to also match on paper titles... So yeah it would be more intuitive if it did. ;-P

Let me close this and open another issue for a different problem on the same paper. :)

**Comment by Phyks** [comment]
> Yeah, I expected this field to also match on paper titles... So yeah it would be more intuitive if it did. ;-P

Definitely agree with this :)
