### ISSUE TITLE
Discrepancies in ORCID badge

### ISSUE THREAD

**Issue by Phyks** [dissemin/dissemin#731]
When doing a search by author/ORCID, the ORCID badge sometimes links to the ORCID website and sometimes links to the ORCID profile on Dissemin (`orcid.org/<ORCID>` vs `dissem.in/<ORCID>`) while the researcher name next to it sometimes links to ORCID profile in Dissemin and sometimes links to the researcher profile with slug URL.

It seems that it depends on the type of match as such different papers have the name in bold or not on the researcher page.

**Comment by beckstefan** [comment]
This is to #708 solving #660. The link varies whether there is a dissemin profile or not.

The name is bold if it coincides with the logged in researcher. This wasn't changed.

**Comment by Phyks** [comment]
This is probably pre-existent to #708, I don't remember seeing anything which could cause these discrepancies when reviewing #708. :)

Looking at https://dissem.in/search/?authors=0000-0001-5318-3910, the third paper (https://dissem.in/p/93892618/transport-and-adsorption-under-liquid-flow-the-role-of-pore-geometry) is different from the others.

On https://dissem.in/r/23061/francois-xavier-coudert, all the papers are displayed and only the third one has a bold name (from 2017). I am fully logged out.

I think this is a bit misleading for users why all of this is different. Not 100% sure about the logic in the template, I should have a deeper look at it.

**Comment by beckstefan** [comment]
Ok, I got you wrong there. And yes, it's bold if it's the author who's searched matches. Sorry about that.

To me https://dissem.in/p/93892618/transport-and-adsorption-under-liquid-flow-the-role-of-pore-geometry looks fine but the others are wrong.

Looking at the template I see that for some papers `author.researcher_id` evaluates to `false`. Nevertheless `author.orcid` carries a valid value.

**Comment by Phyks** [comment]
> Ok, I got you wrong there.

No problem, I made a quick issue, probably would have deserved a bit more details anyways :)


> To me https://dissem.in/p/93892618/transport-and-adsorption-under-liquid-flow-the-role-of-pore-geometry looks fine but the others are wrong.

Definitely agree on this.


> Looking at the template I see that for some papers author.researcher_id evaluates to false. Nevertheless author.orcid carries a valid value.

Indeed! I'm almost sure this is coming from https://github.com/dissemin/dissemin/issues/659 then. Probably a duplicate in the end.

**Comment by wetneb** [comment]
Fixed by #659.
