### ISSUE TITLE
Add instructions to install VirtualBox guest additions to installation instructions

### ISSUE THREAD

**Issue by PierreSenellart** [dissemin/dissemin#734]
I do not know anything about Vagrant. I imagine most people who use it would use VirtualBox as a provider.

When following the installation instructions from a fresh Vagrant install, one obtains the following error message:
```
==> default: Checking for guest additions in VM...
    default: No guest additions were detected on the base box for this VM! Guest
    default: additions are required for forwarded ports, shared folders, host only
    default: networking, and more. If SSH fails on this machine, please install
    default: the guest additions and repackage the box to continue.
    default: 
    default: This is not an error message; everything may continue to work properly,
    default: in which case you may ignore this message.
==> default: Installing rsync to the VM...
==> default: Rsyncing folder: /home/pierre/git/dissemin/ => /vagrant
==> default: Mounting shared folders...
    default: /dissemin => /home/pierre/git/dissemin
Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:

mount -t vboxsf -o uid=1000,gid=1000 dissemin /dissemin

The error output from the command was:
```

This is because the default Vagrant box created does not include VirtualBox guest editions. It seems that this can be easily fixed by installing the VirtualBox Guest Addition plugin for Vagrant:
```
vagrant plugin install vagrant-vbguest
```
but this needs to be done **before** attempting the installation.

It is probably worth adding this to the installation instructions (at least for people using VirtualBox), both in [/doc/sphinx/install.rst](../blob/master/doc/sphinx/install.rst) and in [/README.md](../blob/master/README.md). Can someone who knows Vagrant better than I do check this is correct?

**Comment by Phyks** [comment]
Indeed, with the current Vagrant + Virtualbox setup, guest additions are required. Requiring to install

```
vagrant plugin install vagrant-vbguest
```

before attempting the installation should indeed be the easiest way to ensure this is the case! I agree this would deserve a bit more explanations in the doc.
