### ISSUE TITLE
www.dissem.in should be the main site

### ISSUE THREAD

**Issue by a3nm** [dissemin/dissemin#738]
When going to www.dissem.in, the current configuration leads us to the website association.dissem.in; it should clearly be https://dissem.in.

**Comment by Phyks** [comment]
This issue is two-part. First, there was a misconfiguration issue (failing to define the `ServerAlias` in the HTTPd config), this is fixed.

The remaining issue (on which I cannot act) is that the DNS are not correct. `www.dissem.in` and `prod.dissem.in` both sends to `62.210.110.164` while it should probably be `163.172.220.133` (new server).

**Comment by wetneb** [comment]
Oops, sorry about that! I have just updated the DNS.

**Comment by a3nm** [comment]
I can see the new DNS but now on https://www.dissem.in/ I get an SSL certificate error and a HTTP 400 bad request error.

Probably www.dissem.in should be added to the certificate, and then I'm not sure about where the 400 is coming from?

**Comment by Phyks** [comment]
Still not the case for me:

```
16:18 lverney@mblv ~ % dig +short dissem.in
163.172.220.133
16:18 lverney@mblv ~ % dig +short www.dissem.in
62-210-110-164.rev.poneytelecom.eu.dissem.in.
62.210.110.164
16:18 lverney@mblv ~ % dig +short association.dissem.in
62.210.110.164
```

I see the SSL error though (due to the certificate from `association.dissem.in` being served for `www.dissem.in`). Could you check which DNS answer you get?

**Comment by Phyks** [comment]
Actually, on a clean machine

```
% dig +short prod.dissem.in
62.210.110.164
```

So it seems `prod.dissem.in` is still outdated / unmodified. I'll reissue a SSL certificate for all domains afterwards.

**Comment by wetneb** [comment]
Sorry again, prod.dissem.in just updated.

**Comment by Phyks** [comment]
Thanks! SSL cert is generated and live. The remaining 400 error is due to https://github.com/dissemin/dissemin/pull/749 I think.
