### ISSUE TITLE
"Paper object" in the deposits page

### ISSUE THREAD

**Issue by a3nm** [dissemin/dissemin#739]
In the "My deposits" page for logged in users, papers are presented as "Paper object (xxx)" with xxx being some number. This should instead be the title of the paper.

**Comment by Phyks** [comment]
Could you take a screenshot please? (shame on me, I don't have any deposit through Dissemin)

**Comment by a3nm** [comment]
![https://a3nm.net/share/2019_05_02_744855.png](https://a3nm.net/share/2019_05_02_744855.png)

**Comment by a3nm** [comment]
Yup that's fine for me now, thanks!
