### ISSUE TITLE
Deposits on HAL are a bit unclear

### ISSUE THREAD

**Issue by a3nm** [dissemin/dissemin#740]
When depositing on HAL, dissemin gives a link to the future URL of the deposit (pursuant to #456) but clicking the link results in a message "Document non trouvé" while the deposit is still being processed. The message should be more explicit and say that this error is normal and that everything is going on fine.

Ideally of course it would be better on HAL's side if, while they are doing their moderation, the future URL of the deposit could show something else than "Document not found". Has this been suggested to them?

**Comment by Phyks** [comment]
> Ideally of course it would be better on HAL's side if, while they are doing their moderation, the future URL of the deposit could show something else than "Document not found". Has this been suggested to them?

:+1: for this.

> When depositing on HAL, dissemin gives a link to the future URL of the deposit (pursuant to #456) but clicking the link results in a message "Document non trouvé"

I got an issue with this as well recently. On the paper page, it is quite clear with the banner. But I think the HAL link pending moderation should probably not appear in the "Links" section in the right sidebar.

**Comment by wetneb** [comment]
No it has not been suggested to HAL to change their interface in this regard.

**Comment by beckstefan** [comment]
It makes some sense to indicate a 404 for repository while the publishing process is still ongoing. The resource is not yet available. Ideally there would be a HTTP status for "probably here will be some content in the near future".

Aside from that, for TUprints there's a similar issue. So maybe we change our text and omit the link with the future resource.

**Comment by wetneb** [comment]
Perhaps one way to do this would be to hide OaiRecords associated with a DepositRecord that is not published yet? When we change the status of the DepositRecord, we should make sure we update the OaiRecord and the Paper accordingly.

**Comment by beckstefan** [comment]
Both happens already. Well, the OaiRecord is not hidden, but on the paper detail page there is an alert informing that there is an ongoing deposit.

**Comment by wetneb** [comment]
Ok, then I don't know what else we can do. Do you want me to get in touch with HAL to suggest a change on their side, perhaps?

**Comment by beckstefan** [comment]
No. My suggest is to simply change our own text, i.e. removing the future link.

**Comment by wetneb** [comment]
Oh ok, sure, that totally makes sense.
