### ISSUE TITLE
Papers missing for people with an empty ORCID profile

### ISSUE THREAD

**Issue by a3nm** [dissemin/dissemin#746]
To reproduce:

1. Search for "Jean-Frédéric Gerbeau"
2. On [this result page](https://dissem.in/search/?authors=Jean-Fr%C3%A9d%C3%A9ric+Gerbeau), click on the [link](https://dissem.in/0000-0002-4522-4329/) to the name of the first author of the first paper.
3. Notice that the page which says "No paper found", which is confusing as the page should at least show the paper on whose author the user just clicked.

The user https://orcid.org/0000-0002-4522-4329 has no publications on his ORCID profile. I'm not sure whether Dissemin fetched that list and noticed it is empty, or whether Dissemin didn't even try to fetch it (as the user probably hadn't used the site yet).

Of course, it can be the right behavior for the page https://dissem.in/r/143815/jean-frederic-gerbeau to show different things: maybe the user manually removed some paper from their profile (on Dissemin, or conceivably on ORCID). Yet, in the very common case where the user has no publication on their ORCID profile and has never logged into Dissemin, one would expect this page to list all papers known to Dissemin where a user has the corresponding ORCID.

**Comment by wetneb** [comment]
Fixed by #694.
