### ISSUE TITLE
Model for Licences

### ISSUE THREAD

**Issue by beckstefan** [dissemin/dissemin#761]
Licenses are currently hard-coded in the source.

Move them to a model with option for translation with https://pypi.org/project/django-modeltranslation/

Related to #364

**Comment by beckstefan** [comment]
I just found https://github.com/ecometrica/django-vinaigrette which looks nice and less heavy than django-modelstranslation.

It uses regular django translation, so in theory should work with translatewiki. However, somehow the production server would need to be involved in the process as there are new string for translation generated.

Any opinions on that?

**Comment by wetneb** [comment]
Nice! It could be a good fit indeed.
