### ISSUE TITLE
Adding translation validators on Translatewiki.net

### ISSUE THREAD

**Issue by Abijeet** [dissemin/dissemin#792]
Greetings,

I work on the @translatewiki team. 

We've recently developed a new validator framework that block translators from saving translations that have errors. Errors vary based on the project and have to be configured accordingly. 

Based on past requests [[1](https://phabricator.wikimedia.org/T204568#4971934)][[2](https://gerrit.wikimedia.org/r/c/translatewiki/+/491980)], we've identified Dissemin as a project to test the new validator framework with.

**What validations do translations need?** 
Translatable strings often contain markup that should be retained as-is in the translation. Typing that markup can be slow and difficult because special characters are common. Translatewiki can provide translators a button clicking on which inserts the piece of markup into the translation to the current cursor position. In addition, if a translation is missing that specific markup, Translatewiki can either warn the translator or simply reject the translation, since such markup is usually mandatory to display the messages properly to the end user.

We've analyzed the strings present in Dissemin and have come up with the following insertables,

1. `%d`, `%s`
2. `%(doctype)`, `%(deposit_url)`
3. `{{PLURAL:GETTEXT|%s paper found|%s papers found}}`

The plan is that if the English text has any of these strings, than the translation must contain them too. If it is not present, the translator will not be able to save the translation. We can also make it so that the translator is just warned but is still allowed to save the translation.

Please let us know if we can go forward with this and if you have any other inputs.

**Comment by wetneb** [comment]
This is great, thank you very much! I tried doing that myself but was stuck by my lack of knowledge of Translatewiki.

I do not know gettext very well but I have doubts about your third insertable: is `{{PLURAL:GETTEXT|%s paper found|%s papers found}}` really supposed to be present in the target language (non-English), since it contains some English text?

As far as I understand, the simplest solution would be to have a validator that directly captures the rules of gettext as used by Django (which would be useful to other Django projects hosted by Translatewiki). This would also be more future-proof, since we would not need to update the validator if new translatables are introduced with new variable names in them (such as `%(doctype)`). But in any case the validator you propose should already be useful in the current situation (and I am not in a position to develop a full Django validator myself).

**Comment by Abijeet** [comment]
Hi @wetneb,

Thanks for your quick response.

> I do not know gettext very well but I have doubts about your third insertable: is {{PLURAL:GETTEXT|%s paper found|%s papers found}} really supposed to be present in the target language (non-English), since it contains some English text?

Yes, you are right. It would contain non-English text, but we can ensure that there is a piece of text that starts with `{{PLURAL:GETTEXT|` and ends with `}}`. We could also validate that based on the language, it contains the correct number of plural forms.

>  since we would not need to update the validator if new translatables are introduced with new variable names in them (such as %(doctype))

Insertables check for insertables using regex in the source message. In this case, we would write a single insertable with the regex - `/\%\([a-zA-Z_]+\)/` which would match - `%(doctype)`, `%(deposit_url), `%(num_total)` etc.

I've prepared an initial patch for adding the new validators here - https://gerrit.wikimedia.org/r/c/translatewiki/+/519783

If the translators miss these strings would you like them to be simply warned or should we stop them from saving the translation altogether?

**Comment by Abijeet** [comment]
Thanks. Is it OK if we keep this open until the validators are added and deployed on Translatewiki.net? It might take a 3-4 of weeks as some of us are going on vacation starting next week.

**Comment by wetneb** [comment]
Of course!

**Comment by wetneb** [comment]
Here is an instance of Translatewiki commit which recently broke the build: 1c60f541a6. The problem was the syntax of variables: `... vuonna %(year) julkaisijana ...` should be `... vuonna %(year)s julkaisijana ...`.

Just including this here as an example to help develop appropriate validators.

**Comment by Abijeet** [comment]
Hmm, so in `%(year)s`, the `s` is also part of the variable? I also see `%(doctype)s`, `%(deposit_url)s`, `%(repo_url)s`. So it seems the `s` is part of the variable format. 

Are there any possible characters that can be introduced other than `s`? Can it be multiple characters or will it always be a single character?

**Comment by wetneb** [comment]
Yes the `s` is part of the variable format. It indicates that the variable will be replaced by a string. When it is replaced by a number, the `d` letter is used instead, as in:

`we found %(num_papers)d papers`

This enables localization with plurals.

As far as I am aware these are the only two types available, but I could not find an exhaustive documentation about that. The best I could find is:
https://docs.djangoproject.com/en/2.2/topics/i18n/translation/

**Comment by wetneb** [comment]
Another example today:

```
#: vinaigrette-deleteme.py:26
msgid "Christian pastoral practice & religious orders"
msgstr "\nPráctica pastoral cristiana y órdenes religiosas"
```
gives the error `'msgid' and 'msgstr' entries do not both begin with '\n'`.
(Travis build: https://travis-ci.org/dissemin/dissemin/jobs/575657617, commit: https://github.com/dissemin/dissemin/commit/393f0365aee5d86211e3e16957fdcb9632ef42e9#diff-b63ff36b3dc755c1c4ea2ccf54080b76R2393).

**Comment by Abijeet** [comment]
Greetings @wetneb 

As per our discussion, we've added the following validators and deployed them to Translatewiki.net. 

1. `%s / %d` variable validator
2. `%(variable)type` variable validator
3. Newline validator - Ensure newlines match between translations and source string.
4. Plural validators

You can [test them out](https://translatewiki.net/wiki/Special:Translate?action=translate&group=dissemin&language=en&filter=%21translated) to see if you'd like us to tweak anything. I've also added some screenshots to the [Phabricator ticket](https://phabricator.wikimedia.org/T231658#5503711).

**Comment by wetneb** [comment]
Hey @Abijeet,

That's absolutely fabulous!!!

On behalf of the team, thank you so much for this hard work! We are very grateful, this is something that will make it significantly easier for us to maintain Dissemin.

Much Wikilove to you and the rest of the Translatewiki team ❤
