### ISSUE TITLE
HAL deposits are failing

### ISSUE THREAD

**Issue by Phyks** [dissemin/dissemin#794]
Starting from now, we start having a bunch of errors about HAL deposits failing. This is due to HAL switching (and enforcing) to HTTPS with a 301 redirect, which is not supported by the current code relying on `http.client`.

Quick fix is to change the API endpoint manually, to enforce HTTPS on our side. That is `http://api.archives-ouvertes.fr/sword/hal` should be `https://api.archives-ouvertes.fr/sword/hal`.

Better fix (longer term), we should move out to some higher level API able to handle such redirects, such as `requests`: https://github.com/dissemin/dissemin/blob/16401e19f2432570b11398d963b8381909abb28f/deposit/hal/protocol.py#L171-L187.

<s>Note: By quickly going through the code, it seems [this comment](https://github.com/dissemin/dissemin/blob/master/deposit/hal/protocol.py#L69-L70) might be out of date and require a trailing `hal` in the URL. To be checked.</s>

**Comment by wetneb** [comment]
We concatenate the `hal` later on, so the comment is still current:
https://github.com/dissemin/dissemin/blob/be00cd13270f31f8ed547f0f5bb1038ae33cf689/deposit/hal/protocol.py#L169
