### ISSUE TITLE
Failing CI build due to wand error

### ISSUE THREAD

**Issue by beckstefan** [dissemin/dissemin#803]
Currently CI fails because wand raises an error.

This is due to the fact, that Travis now uses Ubuntu 16 instead of 14.

In Ubuntu 16 imagemagick's pdf support is considered as a security risk and deactivated.

To fix this, we have to change `/etc/ImageMagick-6/policy.xml` and make pdf readable.

`<policy domain="coder" rights="read" pattern="PDF" />`

**Comment by beckstefan** [comment]
Fixed by https://github.com/dissemin/dissemin/commit/3941fb1f9a32bf345b6d03b761eeea14daade395

**Comment by wetneb** [comment]
Thank you so much for taking care of this Stefan!
