### ISSUE TITLE
Flexible letter of declaration

### ISSUE THREAD

**Issue by beckstefan** [dissemin/dissemin#826]
Currently the letter of declaration must be reprogrammed with reportlab (or any other pdf-generator).

As pointed out by @Phyks in #816, we could try to fill in form in pdfs and offer these, as this should be simpler.

I see only one downside: Afterwards the user can change things (like the license), resulting in extra work for the repository administrations.

Additionally, we still should ship the identifier that we got from the repository.

**Comment by Phyks** [comment]
> I see only one downside: Afterwards the user can change things (like the license), resulting in extra work for the repository administrations.

User could anyway update the current generated PDF prior to signing it :)

**Comment by beckstefan** [comment]
> User could anyway update the current generated PDF prior to signing it :)

Definitely yes, but it's not as trivial ;-)

**Comment by beckstefan** [comment]
I close this, as I think that it's possible with the current setup.

The letter of declaration is individual for each institution as it is a legal document. Thus, we have to set a letter of declaration per repository. PDFs for different institutions must thus be filled in differently, requiring some python actions depending on the institution.

In the current setup it is not important, what the generating function for an institution does as long as it returns a PDF. So it can fill in PDF forms an return filled in PDF.
