### ISSUE TITLE
Vagrant installation instructions do not work

### ISSUE THREAD

**Issue by rgrunbla** [dissemin/dissemin#834]
Hello,

Right now, trying to set up a dissemin installation with vagrant and virtualbox fails (log below).
[vagrant_up_fail_log.txt](https://github.com/dissemin/dissemin/files/3707796/vagrant_up_fail_log.txt)

This is related to https://github.com/dotless-de/vagrant-vbguest/issues/351, opened two weeks ago but without an ETA.

A possible fix that works for me is https://github.com/dotless-de/vagrant-vbguest/issues/351#issuecomment-538096696

In the meantime, I propose using this fix while waiting for an upstream solution.

**Comment by beckstefan** [comment]
Fixed by #833.
