### ISSUE TITLE
[[Dissemin:eb054a-zenodo/en]] i18n issue

### ISSUE THREAD

**Issue by verdy-p** [dissemin/dissemin#858]
[**URL**](https://translatewiki.net/wiki/Dissemin:eb054a-zenodo/en)
Can someone explain what is this term "zenodo" in the doc? Is it really a proper name, brand or distinctive product/projet/site name ? Why isn't there a capital?

**Comment by beckstefan** [comment]
Thank you for reporting!

This is my fault, since I did something wrong on generating the translation strings.

I have just corrected this and there should be the correct strings on TranslateWiki.

(Same for #859)

**Comment by beckstefan** [comment]
Update on TranslateWiki is done.
