### ISSUE TITLE
Whitespace in translatable strings

### ISSUE THREAD

**Issue by wetneb** [dissemin/dissemin#860]
Some translatable strings seem to contain extra whitespace:
https://translatewiki.net/wiki/Dissemin:c712ee-%3D7B%3D7BPLURAL:GETTEXT%3D7C/fr

This makes translators' life hard.

This can be avoided by using `{% blocktrans trimmed %}` instead of `{% blocktrans %}` when declaring these messages in templates.

**Comment by sayashraaj** [comment]
Hi, I am interested. What is the task exactly?

**Comment by wetneb** [comment]
The message linked to above is defined here:
https://github.com/dissemin/dissemin/blob/abe43f8b7232898756320d65015368f8bb541f44/papers/templates/papers/messages.html#L8-L12

We should add `trimmed` to the opening `{% blocktrans %}` to make sure whitespace around it.

This problem might happen in other places. You could review `locale/django.pot` to see if any other message has whitespace around it, locate the file where it is defined, and add the `trimmed` keyword to fix the issue.

Once you have added the `trimmed` keyword to many places, you can re-generate the translations as indicated in the documentation:
https://dissemin.readthedocs.io/en/latest/localization.html#generating-po-files
You can also submit a pull request without doing this last step: your effort will already be greatly appreciated!

**Comment by nemobis** [comment]
The problem might also be in Translate's [FFS](https://www.mediawiki.org/wiki/Special:MyLanguage/Help:Extension:Translate/File_format_support) for Gettext, although I would have expected us to have noticed earlier in such case. The relevant code is https://phabricator.wikimedia.org/diffusion/ETRA/browse/master/src/Utilities/GettextPlural.php

**Comment by beckstefan** [comment]
> Once you have added the trimmed keyword to many places, you can re-generate the translations as indicated in the documentation:
https://dissemin.readthedocs.io/en/latest/localization.html#generating-po-files

As I explained in the last developer meeting, we need to generate our translation files on `master` of our production environment, otherwise we lose our translations from vinaigrette.

I opened an issue about that: #862

**Comment by beckstefan** [comment]
Locales are updated, TranslateWiki will recognize them with their next update.
