### ISSUE TITLE
Enhance Documentation concerning localisation

### ISSUE THREAD

**Issue by beckstefan** [dissemin/dissemin#862]
Currently our documentation is misleading.

Since we use vinaigrette to translate some few database columns, we need to generate our files on production. Otherwise we lose our vinaigrette translations.

Workflow should be:

1. Developer adds translations string via gettext
2. Merge PR
3. Pull on production
4. Generate files
5. Add files to `master`

Then, the normal step via TranslateWiki applies.

**Comment by wetneb** [comment]
Perhaps we could also run the translation updates on a local instance, if there is an option to keep the existing translations.

**Comment by beckstefan** [comment]
Uhm, yes, there' a `--keep-obsolete` that can be used with `--no-vinaigrette`. But well, it keeps all obsolete.

On the other hand: When doing changes on the database we still need to generate on master.

And still, I think we should not add `*.po` files to a PR, since this can interfere badly (merge conflict).

**Comment by beckstefan** [comment]
Addition: I just checked `--keep-obsolete` in combination with `--no-vinaigrette`.

This does not work, it keeps the vinaigrette messages, but they are commented out.

Another solution could be the following: `vinaigrette` adds a temp file named `vinaigrette-deleteme.py`. Usually deleted, we can keep it with `--keep-vinaigrette-temp`.

This way we get a two-way system:

1. Database translations
  * Run vinaigrette on master with `--keep-vinaigrette-temp`
  * Add `vinaigrette-deleteme.py` to master

2. Normal translation run locally
  * Run makemessages with `--no-vinaigrette`

The latter will collect the strings from `vinaigrette-deleteme.py` -- nothing is lost.

**Comment by wetneb** [comment]
Nice! Thanks a lot for investigating this!
