### ISSUE TITLE
GeoJSON

### ISSUE THREAD

**Issue by beckstefan** [dissemin/dissemin#874]
Currently we have a dependency on *django-geojson*, that is not really used in our code, as far as I can see.

*django-geojson* broke our build, because it has a dependency on *jsonfield*. The latter one has recently had a major update, so that *django-geojson* fails with ``django.core.exceptions.ImproperlyConfigured: `jsonfield` dependency missing. See README.``

So maybe, we can remove the functionality?

(Currently, I have set out dependency on *jsonfield* to ``<3``.)

**Comment by wetneb** [comment]
Yes sure! It was added for the map of institutions but that has never been finished.
