### ISSUE TITLE
Text improvement after upload

### ISSUE THREAD

**Issue by beckstefan** [dissemin/dissemin#900]
Currently it say that the status can be checked in the profile. Should be more explicit about what status.

**Comment by beckstefan** [comment]
Currently is says:

`You can check for the status in your <a class="alert-link" href="{{ my_profile }}">profile</a>.`

My first proposition would be

`You can check the publication progress in your <a class="alert-link" href="{{ my_profile }}">profile</a>.`

**Comment by wetneb** [comment]
Makes sense!
