### ISSUE TITLE
Fix security holes

### ISSUE THREAD

**Issue by wetneb** [dissemin/dissemin#93]
- Add rate-limiting at various places
- …
- ideas ?

**Comment by wetneb** [comment]
a3nm says: 1 requête / 2s max par IP, et se souvenir de quelle IP a lancé quel background job, et abort un job d'une IP si elle lance un job et en a déjà 3 qui tournent

**Comment by RaitoBezarius** [comment]
Here my vague ideas and standard checklist:

[ ] Rate-limiting endpoints which are abusable
[ ] Checking all fields where a user can input markup / text for XSS (proper sanitization of input)
[ ] Controlling the spiders to prevent using the server as an unexpected booter (DDoS server).
[ ] XSRF / CSRF attacks (tokens)
[ ] CORS issues.
[ ] SSL/HTTPS termination.
[ ] SSH protection: fail2ban, no root login, only SSH keys
[ ] 2FA?
[ ] GPG signature for liberation (next level in 2060: put the liberation proof on the blockchain with a Ethereum-like network).
[ ] Firewall / IDS / IPS (lower priority)
[ ] Database security: storing passwords / tokens in a secure way, do not reinvent your own crypto, do not mix crypto, SQL injections (same as XSS concerns)

**Comment by wetneb** [comment]
Closing as too general, we have improved this.
